### ISSUE TITLE
Proyecto de maquetación web basada en diseño en PSD

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/curriculum#1025]
Este issue retoma la conversación iniciada por @developerVilchez hace ya más de un año en #886... :see_no_evil: 

Pensando en aquellas estudiantes que tienen más afinidad por el diseño visual, CSS, etc, qué les parece tener algún proyecto en el que tengan que maquetar usando HTML, CSS y JavaScript una plantilla web basada en un PSD. Es un caso todavía común en la industria. Hay recursos gratuitos como este donde se pueden sacar un montón de PSDs, con todos los assets, fuentes, colores, iconos, imagenes, ... para que transformen un diseño gráfico en una página web.

https://symu.co/freebies/templates-4/blog-psd-template/

Ideas?

cc/ @Laboratoria/coaches

**Comment by mfdebian** [comment]
Sólo para saber que estoy entendiendo bien, PSD son los archivos en formato Adobe Photoshop, no? (si no, qué vergüenza, no sé de qué estás hablando). Creo que sí aporta mucho valor proponer ejercicios del tipo "un cliente te entrega este PSD (o diseño realizado en illustrator u otro), y debes adaptarlo a sitio web (HTML-CSS-JS)"; **Potenciaríamos harto** todos esos perfiles FE que se inclinan mucho más por el diseño de interfaces y satisfacer necesidades de clientes a través de la disciplina UI.

**Comment by lupomontero** [comment]
> PSD son los archivos en formato Adobe Photoshop, no? 

@mfdebian: Sí, a eso me refería. No tienen por qué ser archivos de Photoshop en particular, pero si archivos de diseño con vectores, bitmaps, fuentes, etc (Photoshop, Illustrator, Gimp, InkScape, ...)

**Comment by mfdebian** [comment]
Perfect @lupomontero creo que sí aporta muchísimo valor, me huele a electivo eso sí, no?

**Comment by ElizabethVegaM** [comment]
Me parece super buena idea, opino igual que Alpi que podría potenciar estos perfiles orientados al UI, además de reforzar la parte de CSS en aquellas estudiantes FE que no tienen un acercamiento al diseño o no es su objetivo principal pero quieren practicarlo.

**Comment by dapino** [comment]
Hola!, tenía pendiente participar en este issue. 
Me parece cool la idea de un electivo enfocado en maquetación, creo que es importante definir que habilidad se buscan fortalecer, porque puede ser algo muy enfocado en solucionar interfaces complejas con estilos o algo más enfocado en adaptarse al _workflow_ diseñador --> desarrollador. o Ambos enfoques. 

Así como en algunos proyectos **Diseño** pasa una guía de estilos o un sistema de diseño completo para que **Desarrollo** construya las interfaces con base en eso según las necesidades que vayan surgiendo, hay proyectos en donde se manejan interfaces muy bien definidas _(.ai, .xd, figma, sketch o la herramienta que se esté utilizando)_ y **Desarrollo** tiene que construirlas lo más preciso posible. Por lo general esto depende de la escala del producto y la autonomía.

También es importante saber que un dev puede aportar conocimientos en usabilidad, patrones de diseño, accesibilidad y la habilidad de comunicarse con los diseñadores es algo que no siempre se tiene. 

Yo propondría un reto tipo frontendmentor.io, donde dan una interfaz en figma o sktech y hay que construirla, y un reto de proponer una estructura de una interfaz que solucione algo definido basándose en una guía de estilos y lineamientos.

**Comment by unjust** [comment]
Me gusta la idea. Creo sería mas como electivo que ellxs pueden hacer  - con los proyectos que hay, no sé cual podemos mover o quitar. 
O un opción es tener un social network o burger queen ya diseñado/maquetado que ellxs puedan seguir.
