### ISSUE TITLE
Actualizar objetivos de aprendizaje en proyectos de front-end no estandarizados

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/curriculum#1067]
Actualizar objetivos de aprendizaje en proyectos de front-end que _todava no han sido estandarizados_:

- [ ] :construction: #1118 @lupomontero 
- [ ] [`news-alerts`](https://github.com/Laboratoria/bootcamp/tree/main/projects/04-news-alerts) @mfdebian
- [x] #1130
- [x] #1131
- [ ] #1132

**Comment by mfdebian** [comment]
@Laboratoria/coaches ¡Hola coaches! :heart: Queríamos saber si es que alguien se anima a ayudarnos a refactorizar, para poder publicar, alguno de los proyectos no asignados que tenemos en nuestro roadmap de proyectos :sparkles: 

Consiste en revisar el formato de propuesta de proyecto en el README, actualizarlo a cómo se están escribiendo hoy en día los proyectos de nuestra currícula  y hacer una pequeña implementación modelo de ellos para revisar sus detalles de implementación!

Nos pueden contactar a mi o a @lupomontero para irse sumando, por ahora los proyectos no asignados son:
- [ ] [`battleship`](https://github.com/Laboratoria/bootcamp/tree/main/projects/05-battleship)
- [ ] [`social-network-fw`](https://github.com/Laboratoria/bootcamp/tree/main/projects/05-social-network-fw)
- [ ] [`tic-tac-toe-rn`](https://github.com/Laboratoria/bootcamp/tree/main/projects/05-tic-tac-toe-rn).

**Comment by unjust** [comment]
Este parte: "hacer una pequeña implementación modelo de ellos para revisar sus detalles de implementación"
Es como hacerlo hasta un punto para verificar el boilerplate ? O que consiste...

**Comment by mfdebian** [comment]
¡Hola @unjust!

Eso consiste en realizar una implementación del proyecto que cumpla con los requerimientos funcionales (o criterios de aceptación mínimos) de este, de manera de revisar, identificar, o descubrir algún detalle que quizás a la hora de escribir el enunciado del proyecto, se nos hayan podido pasar por alto.
