### ISSUE TITLE
Mover contenido de wiki a repo (source tree) y actualizar info de proyectos

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/curriculum#1069]
Propongo migrar el [wiki](https://github.com/Laboratoria/bootcamp/wiki) a una carpeta como parte del código fuente y así estar versionado con las mismas versiones que los releases, así como estar sujetas a PRs y code reviews.

**Comment by unjust** [comment]
reescribir el archivo de contributing con el contenido de wiki. y quiza crear una carpeta `docs` si necesitamos mas informacion de wiki.
