### ISSUE TITLE
LIM014 - Issues que vamos viendo durante el desarrollo

### ISSUE THREAD

**Issue by fakel** [Laboratoria/curriculum#1072]
Abro este issue para ir anotando posibles mejoras que se puedan observar en las OHs de la promoción LIM014 que se encuentra actualmente desarrollando este proyecto:

1. En la documentación, por ejemplo en DELETE /order, se requiere parametros de ruta, para las estudiantes que desarrollan backend puede resultar claro a que se refiere porque express explica que son los parametros de ruta, en cambio, para las que desarrollan el cliente del api no, sería bueno agregar un enlace o un apéndice de términos que les puedan ayudar
2. Infinite render loop en React por mal uso del useEffect, veo que suele ser común que les suceda
3. Los Link Headers, son un pain para backend pero más para Front entenderlos https://www.rfc-editor.org/rfc/rfc5988.txt
4. En la documentación del API no se destaca la posibilidad de agregar el claim del rol de "admin" al token JWT en su payload, por ello, las estudiantes que hacen el API y el CLIENTE suelen hacer una petición adicional para pedir datos del usuario y conocer su rol. Sería interesante comentar en la documentación que el token podrían describir el rol del usuario portador.
5. Las estudiantes pierden mucho tiempo entendiendo como configurar Mockoon del lado del front y se empeora si no se coordinan con las que hacen el API. Habrá un pill?
6. En ocasiones, al intentar correr los test E2E en el api, hay un error de spawn EOENT cuando intenta iniciar el API, aparentemente tiene que ver con no poder encontrar NPM, en el ultimo caso que encontré, se cambió el comando de npm start a node index.js para parchearlo.
7. Se debería configurar primero los test E2E antes de codear para que estos guíen el desarrollo pero aparentemente no está claro en la documentación del proyecto API, incluso no es claro que los E2E están listos.
8. En API chequear test de auth linea 27
9. El globalSetUp no espera por la creación del user admin
10. BQ-API Error en test e2e orders.spec.js línea 43, client está dentro de products, documentación dice que debe estar afuera.
11. BQ-API Los test de órdenes no mandan client en el body y según la documentación es obligatorio por lo que, al usar mongoose, da error de tipo si se puso required
12. El README no invita a usar el docker-compose, pasa totalmente desapercibido

**Comment by betsyvies** [comment]
1.BQ-API, considerar que las imagenes se puedan guardar en base64, ayudaría mucho del lado del cliente si queremos subir una imagen desde el local y no solo como un link en string.
2. BQ-API-CLI, considerar agregar lighthouse como dependencia, ayudaría a las estudiantes con el performace y el PWA.

**Comment by lupomontero** [comment]
@fakel y @betsyvies por el feedback :star: 

Para entender mejor el issue, me gustaría 1ero separar los comentarios por _proyecto_. Creo que acá estamos hablando de cosas que afectan principalmente a [`burger-queen-api`](https://github.com/Laboratoria/bootcamp/tree/main/projects/04-burger-queen-api), pero también a [`burger-queen-api-client`](https://github.com/Laboratoria/bootcamp/tree/main/projects/04-burger-queen-api-client) e incluso [`burger-queen`](https://github.com/Laboratoria/bootcamp/tree/main/projects/04-burger-queen)... :thinking: 

Dejo respuestas más abajo, pero sería buenísimo dividir este _hilo_ en _issues_ o PRs específicos para cada tema... :pray: 

***

### `burger-queen-api`

> 3. Los Link Headers, son un pain para backend pero más para Front entenderlos https://www.rfc-editor.org/rfc/rfc5988.txt

Quizás el RFC no es la manera más _user friendly_ de aprender sobre _Link Headers_. En mi caso yo siempre he usado la documentación de paginación de la API de GitHub, que hace uso de _link headers_ y sirve como _implementación de ejemplo_. Acá un ejemplo en los docs de GitHub: https://docs.github.com/en/rest/guides/traversing-with-pagination

¿Propondrían _quitar_ la idea de paginación y _link headers_ de la especificación del proyecto, reemplazarlo por alguna alternativa, o quizás tratar de documentar/explicar mejor la idea y cómo llevarla cabo? :thinking: 

> 4. En la documentación del API no se destaca la posibilidad de agregar el claim del rol de "admin" al token JWT en su payload, por ello, las estudiantes que hacen el API y el CLIENTE suelen hacer una petición adicional para pedir datos del usuario y conocer su rol. Sería interesante comentar en la documentación que el token podrían describir el rol del usuario portador.

Quizás podríamos agregarlo como sugerencia en el readme, o incluso como comentarios en el [_boilerplate_](https://github.com/Laboratoria/bootcamp/blob/826181e73e09f09e7a641094af17aecbf98ecea4/projects/04-burger-queen-api/routes/auth.js).

> 6. En ocasiones, al intentar correr los test E2E en el api, hay un error de spawn EOENT cuando intenta iniciar el API, aparentemente tiene que ver con no poder encontrar NPM, en el ultimo caso que encontré, se cambió el comando de npm start a node index.js para parchearlo.

Hmmm... me queda la duda de si hay un _problema_ en la implementación de las pruebas o si el problema _realmente_ existe en el entorno de ejecución de la estudiantes (básicamente que `npm` no esté disponible en su `PATH`). Si fuera el 2ndo caso creo que es algo que toca solucionar ad-hoc con la estudiante (nosotrxs echando una mano). Quizás una nota y/o links sobre instalación de Node.js (que incluye `npm`) y temas de terminal como `env` y `PATH` puedan ser útiles...

> 7. Se debería configurar primero los test E2E antes de codear para que estos guíen el desarrollo pero aparentemente no está claro en la documentación del proyecto API, incluso no es claro que los E2E están listos.

:+1: Se agradece PR sugiriendo como enfatizar esto en readme :wink: 

> 8. En API chequear test de auth linea 27

@fakel, puedes porfa agregar un poco más de contexto sobre este punto? Algún mensaje de error en particular? Te refieres a [esta línea](https://github.com/Laboratoria/bootcamp/blob/826181e73e09f09e7a641094af17aecbf98ecea4/projects/04-burger-queen-api/e2e/auth.spec.js#L27)?

> 9. El globalSetUp no espera por la creación del user admin

Buen punto :detective: ... hace tiempo que no reviso ese script. Me da la impresión de que el script no hace mención al usuario admin, con lo cual asumo que o las pruebas asumen que ya existe, o espera que se cree solo al arrancar la aplicación pasando las variables de entorno con credenciales de admin, ... quizás podríamos sugerir en el _boilerplate_ que la creación del usuario _admin_ ocurra _antes_ de que el servidor comience a escuchar peticiones. Si no me falla la memoria, a la hora de registrar las rutas estamos usando _callbacks_ ([`mainNext` en el _boilerplate_](https://github.com/Laboratoria/bootcamp/blob/826181e73e09f09e7a641094af17aecbf98ecea4/projects/04-burger-queen-api/routes/auth.js#L7)) para que puedan hacer cosas asincronas al inicializarse (como crear el usuario admin en caso fuera necesario) y de esa forma asegurarnos que esas cosas se han completado _antes_ de [invocar el método `.listen()` sobre el servidor](https://github.com/Laboratoria/bootcamp/blob/826181e73e09f09e7a641094af17aecbf98ecea4/projects/04-burger-queen-api/index.js#L29). Si se enfoca de esta manera el problema de _esperar_ a que el servidor esté _listo_ (y que usuario admin esté también listo) desaparece, ya que el servidor solo comenzaría a aceptar peticiones HTTP una vez que todos los callbacks de las rutas (`nextMain` en el boilerplate) se hayan ejecutado. ¿Cómo lo ven? ¿Hay algo que no esté viendo? :see_no_evil: 

> 10. BQ-API Error en test e2e orders.spec.js línea 43, client está dentro de products, documentación dice que debe estar afuera.

Tienes razón. Esto sí me parece que es un error en la prueba en sí. Te animas con un PR chquito con ese fix?

> 11. BQ-API Los test de órdenes no mandan client en el body y según la documentación es obligatorio por lo que, al usar mongoose, da error de tipo si se puso required

Esto, al igual que el punto anterior, creo que es una discrepancia entre las pruebas e2e del proyecto, que las hicimos para la versión original del proyecto, cuando se llamaba `bq-node`, y la revisada que le dio @merunga al convertirse en el `burger-queen-api` actual, que es cuando se agregan los docs.

Voy a revisar mi implementación de ejemplo y adaptarla a la definición actual del proyecto para revisar las pruebas e2e en general y posibles discrepancias con los docs. Sería buenazo si pueden compartir links a sus implementaciones de ejemplo para tener más de una referencia.

> 12. El README no invita a usar el docker-compose, pasa totalmente desapercibido

No sé si pudiste ver el archivo [`GETTING-STARTED.md`](https://github.com/Laboratoria/bootcamp/blob/826181e73e09f09e7a641094af17aecbf98ecea4/projects/04-burger-queen-api/GETTING-STARTED.md) que se agregó en el _boilerplate_ recientemente con la intención de facilitar y fomentar el setup con `docker` y `docker-compose`. ¿Quizás una nota extra en el readme para promocionar más esa guía?

> 1. BQ-API, considerar que las imagenes se puedan guardar en base64, ayudaría mucho del lado del cliente si queremos subir una imagen desde el local y no solo como un link en string.

Según la [documentación](https://laboratoria.github.io/burger-queen-api/module-products.html) los productos tienen una propiedad que se llama `product.image` que contiene una URL). Efectivamente podríamos almacenar imágenes en la propia URL usando data codificada en base64, pero si vamos a recomendarlo creo que sería bueno también mencionar los pros y contras, así como casos donde puede tener sentido y casos donde no. A lo que me refiero es que almacenar imágenes como string base64 dentro del documento hace que el documento sea mucho más grande, a veces haciendo muy ineficiente las queries y obligándonos a transferir más data de la necesaria entre cliente y servidor (las imágenes normalmente quedan cacheadas en el cliente, por poner un ejemplo). Toca también tener en cuenta el tamaño de las imágenes.

***

### `burger-queen-api-client`

> 1. En la documentación, por ejemplo en DELETE /order, se requiere parametros de ruta, para las estudiantes que desarrollan backend puede resultar claro a que se refiere porque express explica que son los parametros de ruta, en cambio, para las que desarrollan el cliente del api no, sería bueno agregar un enlace o un apéndice de términos que les puedan ayudar

Alguien se anima con PR agregando alguna aclaración y/o link(s) en el readme?

> 5. Las estudiantes pierden mucho tiempo entendiendo como configurar Mockoon del lado del front y se empeora si no se coordinan con las que hacen el API. Habrá un pill?

No me queda muy claro la necesidad o beneficio de usar algo como Mockoon para este proyecto. Personalmente creo que puede ser más fácil hacer los _mocks_ directamente en JavaScript, sin necesidad de un servidor externo. Con esto me refiero que podríamos por ejemplo tener una capa que abstrae acceso a datos (que después  podamos usar en nuestros componentes). Por ejemplo (súper simplificado):

```js
import products from './data/products.json';

export const findMany = () => Promise.resolve(products);

export const findById = id => Promise.resolve(products.find(product => product.id === id));

// etc ...
```

De esa forma, tenemos una API que podemos después reemplazar con otra implementación que haga peticiones reales a un servidor. :thinking: ¿Qué les parece ese tipo de enfoque? Creo que tiene dos grandes beneficios: capa clara de acceso a datos fácil de reemplazar por otras implementaciones y la indirección que crea permite que las pruebas de nuestros componentes sean también más sencillas, teniendo sólo que mockear esta API y no los detalles del servidor, que pueden cambiar. :thinking: :thinking: 

***

### `burger-queen-api-client`, `burger-queen` (u otros proyectos donde usen React)

> 2. Infinite render loop en React por mal uso del useEffect, veo que suele ser común que les suceda

Si alguien se anima, esto creo que amerita o un blog post o un videito. Yo feliz de colaborar con quien se anime.

> 2. BQ-API-CLI, considerar agregar lighthouse como dependencia, ayudaría a las estudiantes con el performace y el PWA.

:+1: @betsyvies, te animas con un PR?

**Comment by unjust** [comment]
cleaning house
