### ISSUE TITLE
Agregar nueva categoría de objetivos de aprendizaje para desarrollo de productos

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/curriculum#1102]
En el proyecto `chat-app` @oxfist propuso agregar una nueva categoría de _objetivos de aprendizaje_ enfocada en habilidades de _desarrollo de producto_. Para agilizar el [_merge_](https://github.com/Laboratoria/bootcamp/pull/1096) inicial del proyecto y que las estudiantes de la extensión del bootcamp lo pudieran usar, decidimos dejar de lado estos objetivos temporalmente hasta que tuviéramos la oportunidad de conversarlos de manera más general, pensando en cómo afectaría a otros proyectos e invitando a más personas del equipo a la conversación.

Los OAs propuestos en `chat-app` son:

```
  - prod-dev/user-stories
  - prod-dev/acceptance-criteria
  - prod-dev/dod
  - prod-dev/iterative
  - prod-dev/invest
```

Dejo acá abierta la conversación para ver cómo podemos integrar esto.

cc/ @diegovelezg @merunga

**Comment by lupomontero** [comment]
@lalogf, @merunga: cómo lo ven?

**Comment by merunga** [comment]
Hola perdón por llegar tan tarde a esta conversación.
Me encanta la idea de estos otros OAs. Tanto agile como diseño de productos me parecen dos topics lindos para atacar... pero no en conjunto.
No tengo una preferencia ni por uno ni por otro, pero si me parece chévere abrir el paraguas un poco a uno al comienzo y luego al otro

@moniyama

**Comment by moniyama** [comment]
Hola! Perdón por entrarme en la conversación do nada, pero estaba hablando com merunga sobre algo similar!

Me encanta la idea de los dos OAs... 
Antes de self-paced, hacíamos un proyecto en el medio del curso (after Social Network) en que las estudiantes crean un produto en una semana aproximadamente (3-5 días) con Design Sprint.. y después lo desarrollan un MVP en otros 2 días y lo presentean a empresa. En self-paced, esa dinámica es mucho más difícil y quizás inviable, pero todas las veces que hicimos acá, fué muy rico los aprendizajes que las estudiantes tenían y creo que também seria increíble si lograrmos ponerlos OAs sobre eso (desarrollo de producto/design thinking). Es notable la diferencia durante TF en pitch, producto, en contestar las preguntas, en los retos que son más abiertos/amplios y después de Laboratoria.
