### ISSUE TITLE
Agregar concepto de autorízación vs autenticación en objetivos de aprendizaje

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/curriculum#1104]
Continuando la conversación que se inició en la propuesta del proyecto de `chat-app` (#1096), sería chévere ver cómo podemos agregar el concepto de _autorización_ a los objetivos de aprendizaje, y aprovechar a revisar los objetivos de _auth_ (autenticación?) que tenemos actualmente:

```
auth:
  - jwt
  - password-access-and-storage
```

Este cambio tendría que incluir cambios en:

* [ ] [`learning-objectives/data.yml`](https://github.com/Laboratoria/bootcamp/blob/main/learning-objectives/data.yml)
* [ ] Las traducciones correspondientes en [`learning-objectives/intl/es.yml`](https://github.com/Laboratoria/bootcamp/blob/main/learning-objectives/intl/es.yml) y [`learning-objectives/intl/pt.yml`](https://github.com/Laboratoria/bootcamp/blob/main/learning-objectives/intl/pt.yml)
* [ ] Finalmente actualizar los `project.yml` de los proyectos donde corresponda (todos aquellos donde se incluyan objetivos de aprendizaje de _auth_ y/o _autorización_ (`social-network`, `burger-queen`, `chat-app`, etc).

cc/ @oxfist @mfdebian

**Comment by mfdebian** [comment]
Para comenzar con este issue, los proyectos actuales de la currícula donde son pertinentes estos OA's serían los siguientes:
###### Cualquier referencia a 'auth' hasta ahora hace sólo alusión a `authentication` y no a `authorization`

### Autenticación:

- Social Network (firebase/auth)
- Burger-Queen (firebase/auth)
- Burger-Queen api (auth)
- Notes (firebase/auth)
- Chat App (auth)
- Social Network Frameworks (firebase/auth)

###### (Hasta ahora ni Fleet Management, ni Wordpress Plugin, ni Roman Numerals Slack incluyen un OA asociado a Auth, eso está correcto? @ssinuco @lupomontero)

### Autorización:
###### (para leer/escribir/actualizar/eliminar data)

- Social Network (firebase/firestore)
- Burger-Queen (firebase/firestore)
- Burger-Queen api (db/connection mysql, postgres)
- Notes (firebase/firestore)
- Chat App (db/connection, mysql, postgres)
- Fleet Management (db/connection, postgres)
- Social Network Frameworks (firebase/firestore)
- Wordpress Plugin (db/connection, mysql)

Actualmente hay dos OA's en nuestro [data.yml](https://github.com/Laboratoria/bootcamp/blob/main/learning-objectives/data.yml) que hacen alusión al concepto de autenticación, un OA "general":
```
auth:
  - jwt
  - password-access-and-storage
```
Y uno asociado al OA de firebase:
```
firebase:
  - auth
  - firestore
```
No sé qué preferirían, si dejar esos OAs descritos de esa manera (para hacer una diferenciación entre la autenticación con Firebase de _otras_), o si prefieren que se aúnen, de manera que quede sólo una alusión al OA `auth` de manera más general.

De igual forma, habría que empezar a expresarlo como `authentication` y no sólo `auth`, de manera que no se confunda con el de `authorization` que queremos agregar.

Se agregaría entonces el de `authorization`, qué debería incluir ese OA? A manera de draft podría ir quedando así:
```
authorization:
  - permission
  - permission-level
```

En los archivos que se encuentran en [`learning-objectives/intl/`](https://github.com/Laboratoria/bootcamp/tree/main/learning-objectives/intl) la definición (o descripción) de auth es la siguiente:
`auth: Autenticación`
Habría que refactorizarla a:
`authentication: Autenticación`

Y _propagar_ los cambios donde sea correspondiente.

También habría que agregar el de Autorización siguiendo algún patrón similar del tipo:
`authorization: Autorización`

Para comenzar, ¿Qué opinan?
