### ISSUE TITLE
Proyectos alternativos a Social-Network

### ISSUE THREAD

**Issue by moniyama** [Laboratoria/curriculum#1255]
Hola equipo!

Social network es un proyecto bastaaaante demandante a las estudantes, con un gran salto de aprendizaje.... 
y sinto falta de otros proyectos como alternativas/opciones... algo parecido como cipher y card-validation, que tengan OAs y un readme también similares... o un poco más simple.
Si no me equivoco, hoy solo tenemos el proyecto `visitors` que tiene el mismo nivel 3, pero es bien distinto.. si puede usar frameworks por ejemplo, y me parece out of date (sin OAs)

Así, estaba pensando:
- adaptar `visitors` para usar firebase y todos los objetivos generales para que sea algo parecido a social network. 
- adaptar también emergency-room (nivel 02) como opción a social-network. Me parece ser un proyecto que tiene bastante potencial para usar firebase también. Creo que se puede dejarlo un poco más simple (cómo memory-match en relación a data-lovers), pero aún con firebase para tener un contato com asincronia y firebase..

Qué piensan?

**Comment by mfdebian** [comment]
Como muy bien indicas @moniyama el proyecto `visitors` está pensando justamente para poder ser una alternativa a `social-network` que hoy en día es el único proyecto que estamos ofreciendo a las estudiantes que satisfacen los requerimientos de los proyectos de nivel 3, me gusta mucho la idea de poder empezar a retomar `visitors` para agregarle sus OAs y empezar a pensarlo como proyecto a ofrecer a las estudiantes! :star: Si no me equivoco, puede ser que @lupomontero tenga ya hecha una implementación modelo del proyecto. :muscle:  

Entonces creo que podemos partir por revisar el README y generar el archivo de OAs asociados al proyecto.
