### ISSUE TITLE
Renombrar repo de Laboratoria/bootcamp a Laboratoria/curriculum

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/curriculum#1279]
Como parte de un esfuerzo ordenar los diferentes recursos (repos, dominios, etc) que tenemos en Laboratoria, hemos acordado renombrar este repo de `Laboraoria/bootcamp` a `Laboratoria/curriculum`, y mantener el despliegue en `curriulum.laboratoria.la`, donde se aloja la UI actualmente.

**Comment by lupomontero** [comment]
@mfdebian , algún comentario, duda o sugerencia sobre este tema?

**Comment by unjust** [comment]
No me molesta @lupomontero @mfdebian . Pero me confunde un poco "y mantener el despliegue en curriulum.laboratoria.la, donde se aloja la UI actualmente." curriculum.laboratoria.la es un repo o ambiente aparte?

**Comment by lupomontero** [comment]
@unjust, este repo se despliega como sitio web en el subdominio curriculum.laboratoria.la

**Comment by unjust** [comment]
Podemos hacer eso en el mismo release de curriculum parser? O es demasiado cambios.

**Comment by mfdebian** [comment]
Sólo comentar que me parece que está bien, y preguntar ¿Qué tan prioritario es este cambio en el corto plazo? Como para agendarlo en un release más adelante? o es más bien algo que debería ocurrir _pronto_? @lupomontero

**Comment by mfdebian** [comment]
Nos toca revisar bien cuáles son los _side effects_ de este cambio.

**Comment by mfdebian** [comment]
Hecho :blush: 

https://github.com/Laboratoria/curriculum :fire:
