### ISSUE TITLE
Crear tópico sobre AI Prompting

### ISSUE THREAD

**Issue by mfdebian** [Laboratoria/curriculum#1364]
Mariana Costa nos ha compartido por Slack la necesidad de tener, desde currícula, contenido que ayude a las estudiantes a trabajar con herramientas como [chatGPT](https://chat.openai.com), es por eso que se hace necesario tener un tópico con la información pertinente.

**Comment by mfdebian** [comment]
Le pedí ayuda a mati (@matiashoyld), autor del blog [Descrifr[ando]](https://matiashoyl.beehiiv.com/) para que nos ayude a generar el recurso para las estudiantes, comentó que se sumaría a este esfuerzo para ayudarnos con este issue dentro de lo que su tiempo le permita.

**Comment by unjust** [comment]
no vamos con un topico, hay una guia en desarrollo
