### ISSUE TITLE
Agrega parte de React + Typescript al README de bq api client en PT

### ISSUE THREAD

**Issue by unjust** [Laboratoria/curriculum#1416]
Agregaos este parte al readme, hay que agregarlo al README en PT

https://github.com/Laboratoria/bootcamp/pull/1408/files#diff-bd8faeb944b6453746ff05a76f07fa8e932cb3e9516026b0406c56ea693a55f8R140-R150

**Comment by DeysiVergara** [comment]
https://github.com/Laboratoria/curriculum/pull/1572
