### ISSUE TITLE
Implementacion de ejemplo de BQAC Angular

### ISSUE THREAD

**Issue by ssinuco** [Laboratoria/curriculum#1464]
- Implementacion de ejemplo de BQAC en Angular
- Documentacion de buenas practicas que el equipo de coaches recomendara a las estudiantes para estos proyectos

https://github.com/Laboratoria/impl-burger-queen-api-client-angular

(Voy asignar a @Luandrada oficialmente cuando tenemos ella en el org)

**Comment by unjust** [comment]
Diria que no tiene que ser el proyecto completo. O quiza mas de un modelo - algunos acuerdos de buenas practicas con ejemplos.

**Comment by ssinuco** [comment]
La implementacion fue finalizada!
