### ISSUE TITLE
Implementacion de ejemplo de BQAPI MongoDB

### ISSUE THREAD

**Issue by ssinuco** [Laboratoria/curriculum#1465]
- Implementacion de ejemplo de BQAPI con MongoDB
- Documentacion de buenas practicas que el equipo de coaches recomendara a las estudiantes para estos proyectos

**Comment by unjust** [comment]
Si, quizas no una ejemplo completo pero partes.
Donde viviria algo asi - todo en un repo privado. O Coda + repo?

**Comment by unjust** [comment]
En una conversacion hablamos de creamos un repo por esos proyectos con guia y un nomenclatura / titulo para podemos buscar en los repos de Laboratoria. algo como `modelo-burger-queen-api-mongo` (`modelo` o un prefix, el nombre de proyecto, y stack)

Creo en algun repo tenemos un poco codigo de este proyecto con Mongo, o podemos preguntar.

Con la persona que toma este issue debemos definir algunos practicas, ejemplos, detalles que queremos mostrar en el modelo.

**Comment by mfdebian** [comment]
Sólo comento para agregar que ya existe un repo privado con distintas implementaciones modelos de los proyectos, se llama [coach-projects](https://github.com/Laboratoria/coach-projects), en mi opinión no es necesario crear _otro_ repo, si es que este ya cumple con lo que se necesita :blush:

**Comment by ssinuco** [comment]
Cierro este issue porque ya no es prioridad teniendo en cuenta el issue #1753

**Comment by ssinuco** [comment]
Cierro este issue porque ya no es prioridad teniendo en cuenta el #1753

**Comment by ssinuco** [comment]
Cierro este issue porque ya no es prioridad teniendo en cuenta el #1753
