### ISSUE TITLE
Java: Agregar a la currícula java + spring boot + hibernate como OAs

### ISSUE THREAD

**Issue by merunga** [Laboratoria/curriculum#1500]
El objetivo es agregar a [los OAs](https://github.com/Laboratoria/bootcamp/blob/main/learning-objectives/data.yml) de la currícula, todo lo relacionado a java.
Además **para cada OA** debemos alimentar las traducciones y **al menos un recurso** en [español](https://github.com/Laboratoria/bootcamp/blob/main/learning-objectives/intl/es.yml) y [portugués](https://github.com/Laboratoria/bootcamp/blob/main/learning-objectives/intl/pt.yml)

O objetivo é adicionar aos [OAs](https://github.com/Laboratoria/bootcamp/blob/main/learning-objectives/data.yml) do currículo tudo o que estiver relacionado a java.
Além disso, **para cada OA** temos que alimentar as traduções e **pelo menos um recurso** em [espanhol](https://github.com/Laboratoria/bootcamp/blob/main/learning-objectives/intl/es.yml) e [português](https://github.com/Laboratoria/bootcamp/blob/main/learning-objectives/intl/pt.yml).

**Comment by NaraSakamoto** [comment]
Adicionei alguns OAs para Java. Ainda precisamos adicionar OAs para Hibernate e Spring. 

PR:
https://github.com/Laboratoria/bootcamp/pull/1525/
