### ISSUE TITLE
Java: Crear README del proyecto introductorio enfocado sólo en Java

### ISSUE THREAD

**Issue by merunga** [Laboratoria/curriculum#1501]
Un proyecto de línea de comando que tenga como objetivo aprender lo básico de cómo configurar Java, cómo funciona desde la terminal, así como los conceptos fundamentales de OOP.
Aquí sólo se aprende Java, nada más.
Duración esperada: 1-2 sprints.
El readme debe contener un diagrama de classes explicando cómo se espera que se modele la solución.

**Comment by merunga** [comment]
Esta es la propuesta inicial del proyecto:

**Nombre:** Guess the number

**Descripción:**
Crear en la terminal un juego por turnos en el que una usuaria se enfrente a la computadora para adivinar un número aleatorio entre 1 y 100. La jugadora y la computadora irán turnándose para adivinar el número hasta que alguna de ambas acierte el número. El juego debe proporcionar información a la jugadora después de cada turno, indicando la suposición y nombre del jugador del ultimo turno (persona o computadora) y si la suposición era demasiado alta, demasiado baja o correcta. De no adivinar, pasa el turno a la computadora y repetir el proceso.

**Comment by ssinuco** [comment]
Mariano, que te parece si el limite inferior y superior tambien se le pide a la usuaria? Aqui da chance para que se hagan mas validaciones.

**Comment by merunga** [comment]
@vivieall esto lo generé con AI alimentando los otros READMEs, no se si sirve

# Juego de Adivinar el Número

## Preámbulo

En este proyecto, se debe crear un juego por turnos en el que una usuaria se enfrente a la computadora para adivinar un número aleatorio entre 1 y 100. El objetivo es proporcionar una experiencia interactiva y divertida para la jugadora.

## Resumen del proyecto

El juego consiste en que la jugadora y la computadora se turnen para adivinar el número secreto. Después de cada turno, se mostrará información sobre la suposición realizada, indicando si fue demasiado alta, demasiado baja o correcta. El juego continuará hasta que alguna de las dos adivine el número.

## Consideraciones generales

- El juego se desarrollará en la terminal.
- Se utilizará un número aleatorio entre 1 y 100 como número secreto.
- La jugadora y la computadora se turnarán para adivinar el número.
- Después de cada turno, se mostrará información sobre la suposición realizada.
- El juego terminará cuando alguna de las dos adivine el número.

## Criterios de aceptación mínimos del proyecto

- La jugadora y la computadora deben poder adivinar el número secreto.
- Después de cada turno, se debe mostrar información sobre la suposición realizada.
- El juego debe indicar si la suposición fue demasiado alta, demasiado baja o correcta.
- El juego debe terminar cuando alguna de las dos adivine el número.

## Consideraciones técnicas

- El juego se desarrollará en la terminal utilizando un lenguaje de programación como JavaScript o Python.
- Se utilizarán estructuras de control como bucles y condicionales para implementar la lógica del juego.
- Se pueden utilizar funciones para modularizar el código y facilitar su mantenimiento.
- Se pueden utilizar librerías o módulos externos para generar números aleatorios.

¡Diviértete creando el juego de adivinar el número!

@unjust

**Comment by vivieall** [comment]
@merunga Esta sería la propuesta 0.1:

### **Guess the Number - Adivinar el Número**

### **Preámbulo**

En la actualidad, Java es uno de los lenguajes de programación más utilizados en el mundo. A pesar de la diversidad de plataformas y herramientas disponibles, es esencial tener una base sólida en los conceptos fundamentales de Java y la programación orientada a objetos (OOP). El objetivo de este proyecto es introducirte en el mundo de Java mediante un juego sencillo y entretenido. Para este proyecto, se deberá crear un juego por turnos en el que una usuaria se enfrente a la computadora para adivinar un número aleatorio entre 1 y 100. El objetivo es proporcionar una experiencia interactiva y divertida para la jugadora.

### **Resumen del proyecto**

Es un juego interactivo que se lleva a cabo en la terminal, en el que la jugadora y la computadora toman turnos para intentar adivinar un número aleatorio entre 1 y 100. Tras cada intento, se ofrece una pista que indica si la suposición fue demasiado alta, demasiado baja o acertada. El juego prosigue hasta que el número es correctamente adivinado por alguna de las dos participantes (computadora y usuaria).

### **Consideraciones generales**

- Duración del proyecto: Se estima que este proyecto tomará entre 1 y 2 sprints.
- Enfoque exclusivo en Java: A lo largo de este proyecto, el enfoque estará únicamente en el lenguaje Java. No se introducirán otras tecnologías o lenguajes.
- El juego se desarrollará en la terminal.
- Se utilizará un número aleatorio entre 1 y 100 como número secreto.
- La jugadora y la computadora se turnarán para adivinar el número.
- Después de cada turno, se mostrará información sobre la suposición realizada.
- El juego terminará cuando se adivine el número.

### **Diagrama de clases**

En la estructura propuesta para el juego, se sugiere dividir la lógica y las entidades en varias clases para mantener el código organizado y modular. A continuación, se describe el diseño básico de las clases:

**GameLogic**

**Propósito:** Esta clase es el corazón del juego. Maneja la lógica principal, decide qué jugador toma el siguiente turno y evalúa las suposiciones.
**Atributos:**

- `randomNumber`: Guarda el número aleatorio entre 1 y 100 que los jugadores deben adivinar.

**Métodos:**
- `startGame()`: Inicia el juego y genera el número aleatorio.
- `checkGuess(int)`: Evalúa la suposición del jugador y proporciona feedback sobre si la suposición es demasiado alta, demasiado baja o correcta.\

**Player**

**Propósito:** Representa a la jugadora humana. Proporciona la funcionalidad para que la jugadora haga suposiciones.
**Atributos:**

- `name: El nombre del jugador.`

**Métodos:**

- `guess()`: Permite a la jugadora introducir su suposición.
- `getName()`: Devuelve el nombre de la jugadora.\



**Computer (hereda de Player)**

**Propósito**: Representa a la computadora como jugador. Hace suposiciones automáticas basadas en la lógica definida.

**Métodos:**

- `autoGuess()`: La computadora realiza una suposición. Esta podría estar basada en alguna lógica (por ejemplo, búsqueda binaria) o ser completamente aleatoria.


**Relaciones:**
- La clase GameLogic interactúa con las clases Player y Computer para gestionar el juego.
- La clase Computer es una subclase de Player, lo que significa que hereda todas las propiedades y métodos de Player, pero también tiene algunas características adicionales propias.

```
+------------------+
|     GameLogic    |
+------------------+
|- randomNumber    |
|------------------|
|+startGame()      |
|+checkGuess(int)  |
+------------------+

+--------------+
|   Player     |
+--------------+
|- name        |
|--------------|
|+guess()      |
|+getName()    |
+--------------+
      ^
      |
+--------------+
|  Computer    |
+--------------+
|+autoGuess()  |
+--------------+

```

Este diseño de clases permite separar las responsabilidades, facilitando la mantenimiento y posibles extensiones del juego en el futuro. Por ejemplo, podríamos añadir diferentes estrategias para la suposición automática de la computadora o incluso introducir niveles de dificultad.


### **Criterios de aceptación mínimos del proyecto**

- La jugadora y la computadora se alternarán en turnos para intentar adivinar dicho número.
- Tras cada intento, se debe mostrar:
    - El nombre del jugador (persona o computadora).
    - La suposición que se hizo.
    - Un mensaje que indique si la suposición fue demasiado alta, demasiado baja o correcta.
- El juego finalizará en cuanto la jugadora o la computadora acierte el número secreto.

### **Consideraciones técnicas**

- El juego se llevará a cabo en la terminal haciendo uso de Java.
- La lógica del juego se basará en estructuras de control, incluyendo ciclos y sentencias condicionales.
- Se recomienda emplear funciones para segmentar el código y mejorar su legibilidad y mantenimiento.
- Es posible hacer uso de bibliotecas o paquetes adicionales para la generación de números aleatorios.

**¡Diviértete con este desafío de construir el juego de adivinar el número! 🎲🎮**

**Comment by merunga** [comment]
Les parece si agregamos un requerimiento de ir recordando todos los intentos del jugador humano para hacer uso de un array?
@NaraSakamoto @vivieall @ssinuco

**Comment by NaraSakamoto** [comment]
> 

Sim, poderia armazenar tanto as tentativas do jogador humano quanto do computador e exibir isso.
No readme poderia ter um exemplo de como ficaria essa resposta para guiar as estudantes.

----
Sí, podría almacenar los intentos de jugadores humanos y de computadora y mostrarlos.
En el archivo readme, podría haber un ejemplo de cómo se vería esta respuesta para guiar a las estudiantes.
