### ISSUE TITLE
Java: Implementación modelo proyecto 1

### ISSUE THREAD

**Issue by merunga** [Laboratoria/curriculum#1503]
#1501 
debe incluir testing con JUnit

Deberiamos exigir una clase por archivo?

**Comment by merunga** [comment]
Si vamos a agregar el requerimiento de guardar los intentos en un array, habria que modificar esta implementación

**Comment by vivieall** [comment]
@merunga al ser un proyecto introductorio y pequeño, no estoy segura si sea recomendable clase por archivo. Por otro lado, tomando la modificación de guardar los intentos y con base al UML puesto en marcha en el [draft](https://github.com/Laboratoria/bootcamp/pull/1532). El modelo quedaría así: 

```java
import java.util.Random;
import java.util.Scanner;

public class GuessTheNumberGame {
    private static final Random RANDOM = new Random();
    private static final int TARGET_NUMBER = RANDOM.nextInt(100) + 1;

    public static void main(String[] args) {
        System.out.println("Welcome to the Guess the Number game!");

        Player player1 = new HumanPlayer("Player 1");
        Player player2 = new ComputerPlayer("Computer Player");

        boolean gameOver = false;
        int guess;

        while (!gameOver) {
            System.out.println("\n--- Round: " + player1.name + " ---");
            guess = player1.makeGuess();
            gameOver = checkGuess(guess, player1);

            if (!gameOver) {
                System.out.println("\n--- Round: " + player2.name + " ---");
                guess = player2.makeGuess();
                gameOver = checkGuess(guess, player2);
            }
        }
    }

    private static boolean checkGuess(int guess, Player player) {
        player.getGuesses().add(guess);
        
        if (guess < TARGET_NUMBER) {
            System.out.println("Too low!");
        } else if (guess > TARGET_NUMBER) {
            System.out.println("Too high!");
        } else {
            System.out.println("Congratulations, " + player.name + "! You guessed the number.");
            System.out.println("Attempts: " + player.getGuesses());
            return true;
        }
        return false;
    }
}


abstract class Player {
    protected String name;
    protected ArrayList<Integer> guesses;
    
    public Player(String name) {
        this.name = name;
        this.guesses = new ArrayList<>();
    }

    public abstract int makeGuess();

    public ArrayList<Integer> getGuesses() {
        return guesses;
    }
}

class HumanPlayer extends Player {
    public HumanPlayer(String name) {
        super(name);
    }

    @Override
    public int makeGuess() {
        Scanner scanner = new Scanner(System.in);
        System.out.print(name + ", enter your guess: ");
        return scanner.nextInt();
    }
}

class ComputerPlayer extends Player {
    private Random random;

    public ComputerPlayer(String name) {
        super(name);
        System.out.print(random);
        random = new Random();
    }

    @Override
    public int makeGuess() {
        int guess = random.nextInt(100) +  #1;
        System.out.print(name + ", enter your guess: ");
        System.out.print(guess + "\n");
        return guess;
    }
}

```

**Comment by vivieall** [comment]
Aquí probándolo en Intellij:
![image](https://github.com/Laboratoria/bootcamp/assets/13903491/e890d726-c258-4df3-b636-c7575389965e)

@merunga que IDE's se recomendará?

**Comment by merunga** [comment]
Yo estaba pensando q por la familiaridad q ya tienen, fuera el mismo VSCode + [Java Extension Pack](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack) + [Spring Boot Extension Pack](https://marketplace.visualstudio.com/items?itemName=vmware.vscode-boot-dev-pack).
Tb podria ser [JetBrains for education](https://www.jetbrains.com/community/education/#courses)

@vivieall @NaraSakamoto @ssinuco que IDE recomendarían uds?

**Comment by merunga** [comment]
@vivieall en la implementación creo q haria falta hacer el push al array de guesses al llamar a `makeGuess`, no?
Y en lugar de mostrar la cantidad de intentos, mostras los intentos (para tener la necesidad de iterar el array)

**Comment by NaraSakamoto** [comment]
> Yo estaba pensando q por la familiaridad q ya tienen, fuera el mismo VSCode + [Java Extension Pack](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack) + [Spring Boot Extension Pack](https://marketplace.visualstudio.com/items?itemName=vmware.vscode-boot-dev-pack). Tb podria ser [JetBrains for education](https://www.jetbrains.com/community/education/#courses)
> 
> @vivieall @NaraSakamoto @ssinuco que IDE recomendarían uds?

Intellij da JetBrains

**Comment by merunga** [comment]
Requerimientos para IntelliJ
https://www.jetbrains.com/help/idea/installation-guide.html
