### ISSUE TITLE
Pedimos feedback - Form para tomar feedback de estudiantes DEV009 de md links

### ISSUE THREAD

**Issue by unjust** [Laboratoria/curriculum#1505]

**Comment by Davichobits** [comment]
He creado un form para las estudiantes con el objetivo de recibir feeedback sobre el uso del nuevo readme de mdLinks con hitos. Este form está pensado para estudiantes que han podido utilizar ambas versiones: con hitos y clásica.

El formulario lo pueden revisar [aquí](https://forms.gle/oX7KmPpW2jBfJ1rs6):

**Comment by Davichobits** [comment]
@unjust he actualizado el [form ](https://forms.gle/1nU4U7dvu1GWf6Au8) con las consideraciones que pasaste al slack 👌😉

**Comment by unjust** [comment]
Con @Davichobits conversamos que

* Pedimos feedback de los hitos con su segundo grupo en su cohort
* Pedimos feedback de los hitos en primer grupo de cohort DEV011
* Pedimos feedback de hitos + sitio en el segundo grupo de DEV011
