### ISSUE TITLE
falta algunos titles de OAs (algunos de typescript)

### ISSUE THREAD

**Issue by unjust** [Laboratoria/curriculum#1508]
Puede ser solo de typescript pero falta algunos titles traducidos - por ejemplo typescript/basic-types/null-or-undefined.

Aramamos una lista completa y verificamos si es una problema

<img width="933" alt="Screen Shot 2023-08-01 at 11 08 09 AM" src="https://github.com/Laboratoria/bootcamp/assets/92090/bbb3e5b8-c40e-461a-8b15-fc57dbdb2753">

**Comment by mfdebian** [comment]
cerrado en #1556
