### ISSUE TITLE
Dataverse: dataset consideraciones con funcionalidades de proyecto

### ISSUE THREAD

**Issue by unjust** [Laboratoria/curriculum#1576]
Hacemos una version de dataset un poco mas diversa y mientras eso

Agregamos 

- "facts" - un objeto con al menos 3 propiedades. lo mismo propiedades para cada persona, para usar en un filtro
- "imgUrl" - renombramos img a imgUrl
- "shortDescription"
- "description"
- "id" - para enrutamiento en proyecto 3

Arreglamos los tests oas de datatypes para corren y cumplen

**Comment by merunga** [comment]
`facts` reemplaza a `statistics`
