### ISSUE TITLE
urls de topics estan rotos aun

### ISSUE THREAD

**Issue by unjust** [Laboratoria/curriculum#1606]
Quiza no probamos esta fix en staging?
https://github.com/Laboratoria/curriculum/pull/1570

Encontre un PR donde estaba cambiando los urls para funcionar, poniendo los numeros de nuevo
https://github.com/Laboratoria/impl-dataverse/pull/1/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L757

Parece que quiza la redirecion de firebase  espera los numeros en topics (y solo probamos localmente? porque no vi esta problema cuando probe el release). quitamos los redirects?

**Comment by mfdebian** [comment]
Hola @unjust ! el fix sí fue probado en staging, en [este PR](https://github.com/Laboratoria/curriculum/pull/1601)

cuál es el link que aún está arrojando error?

**Comment by unjust** [comment]
@mfdebian los links estan aqui cambiado https://github.com/Laboratoria/impl-dataverse/pull/1/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L757

poe ejemplo

https://curriculum.laboratoria.la/es/topics/javascript/flow-control/loops
https://curriculum.laboratoria.la/es/topics/javascript/flow-control/functions
https://curriculum.laboratoria.la/es/topics/javascript/functions/arrow
https://curriculum.laboratoria.la/es/topics/javascript/basics/variables

me parece ahora cualquier que no tiene numeros el redirect se rompe - pero es mi percepcion solo

**Comment by unjust** [comment]
Confirmamos que todos los links carga bien
