### ISSUE TITLE
El requisito de cumplir todos de tests OA y e2e es muy estricto?

### ISSUE THREAD

**Issue by unjust** [Laboratoria/curriculum#1638]
En los READMEs de Text Analyzer y Dataverse decimos en este parte hay que cumplir todos tests OA, e2e etc.
https://github.com/Laboratoria/curriculum/tree/main/projects/01-text-analyzer#9-consideraciones-para-pedir-tu-project-feedback

Pero creo pueden pasar por Project Feedback si solo falta algunas y hacerlo en el proximo proyecto no? Algunas estudiantes estan dando vueltas cumplir 100% ? Como podemos manejar / mejorar eso?

Issue relacionado:
https://github.com/Laboratoria/curriculum/issues/1583

**Comment by JuanCarlosHM** [comment]
Propongo que lo reestructuremos de la siguiente manera:

Antes de agendar tu Project Feedback con un coach, te sugerimos responder las siguientes preguntas: 

¿Tu proyecto cumple con todos los criterios mínimos de aceptación al ejecutar npm run test:oas?
¿Tu proyecto cumple con todas las pruebas unitarias al ejecutar npm run test?
¿Tu proyecto cumple con todas las pruebas end to end al ejecutar npm run test:e2e?
¿Tu proyecto está libre de errores de eslint al ejecutar npm run test?
¿Has subido tu proyecto a GitHub?
¿Lo has desplegado en GitHub Pages?
¿Tu proyecto tiene un README con la definición del producto?

Recuerda que estas preguntas pueden contribuir a una sesión de retroalimentación más efectiva y beneficiosa en tu proceso de aprendizaje. Si tienes dudas sobre estos puntos puedes consultar con algún coach, ¡Ellos te podrán orientar de mejor manera!

**Importante**:  Antes de tener un ProjectFeedback debes realizar la autoevaluación de objetivos de aprendizaje y life skills desde tu dashboard de estudiante.

**Comment by moniyama** [comment]
Creo q el follow-up en sprint review puede ser interessante para eso y es una buena oportunidad para guiarles.. Recomendarles que pasen o no de proyecto/pidan PF, o recomendarles que foquem la proxima sprint en un oa específico/feature, que hagan x para pasar de proyecto en la proxima sprint etc.. pq creo q es necesario tener un balance entre en tiempo en un mismo proyecto y los oas atingidos (considerando una prioridad de oas).. 

Creo q hay OAs que sí o sí necesitan tener para cambiar de proyecto ("minimo obligatorio"), por eso, debemos guiarles para enfocar en esos primero.... 
Por ejemplo, si ya alcanzaste los OAs "minimo obligatorios" y si aún tiene tiempo (dentro del estimado), les recomendamos que sigues haciendo el proyecto con mas profundidad y alcanzando otros OAs/otras features. 
Si ya están tomando 2 sprints más del estimado (cantidad ejemplo), ya no necesites que cumpla todos los OAs, pero solo los "minimo obligatorio". Si ya lo hicieron, les recomendamos que cambien de proyecto/hagan PF. Si no, que enfoquen en el OAs faltante para que pueda cambiar de proyecto en la proxima sprint.

Y creo que sprint review puede ser interesante por eso, pq podemos tener ideia de cuantas sprints están en el proyecto y cómo les van en sus proyectos.. (perdón si no entendi la discusión y fuera "nonsense" en el topic)

**Comment by unjust** [comment]
Pienso que podemos experimentar con los cambios de parte "Consideraciones para pedir tu Project Feedback" que ha sugerido @JuanCarlosHM.
Y tambien comunica con @marianaLz y los coaches si parte de Sprint Review en estes primeros proyectos puede ser que ellas dar cuenta de los OAs que han logrado y falta,  corriendo sus tests antes de demo o algo - como @moniyama esta explicando.

Esto es lo que hay ahora en Dataverse

> Antes de agendar tu Project Feedback con un coach, asegúrate que tu proyecto:
> 
>  Cumple con todos los criterios mínimos de aceptación al ejecutar npm run test:oas
>  Cumple con todas las pruebas end to end al ejecutar npm run test:e2e
>  Cumple con todas las pruebas unitarias al ejecutar npm run test y que tienen una cobertura del 70% de statements (sentencias), functions (funciones), lines (líneas), y branches
>  Esta libre de errores de eslint al ejecutar npm run pretest
>  Está subido a GitHub y desplegado en GitHub Pages
>  Captura de pantalla del prompt utilizado para generar los datos.
> Tiene un README.md con la siguente:
>  Definición del producto clara e informativa
>  Historias de usuario
>  Un Diseño de la Interfaz de Usuaria (prototipo de alta fidelidad)
>  El listado de problemas que detectaste a través de tests de usabilidad en el README.md
> Tiene un UI que cumple las funcionalidades:
>  Muestra lista con datos y/o indicadores
>  Permite ordenar data por uno o más campos (asc y desc)
>  Permite filtrar data con base en una condición
>  Permite limpiar los filtros con un botón
>  Es responsive
> Recuerda que debes hacer una autoevaluación de objetivos de aprendizaje y life skills desde tu dashboard de estudiante.
>  Si no has completado todo lo anterior, no consideramos que estás lista para tu sesión de Project Feedback.

Podemos separar parte que son requisitos con parte que puede ser preguntas, por ejemplo:

Esegurar que tiene:
```
* Subido tu codigo a github
* has desplegado en GitHub Pages
* Has corrido los tests e2e y las test:oas
* las pruebas unitarias al ejecutar npm run test  tienen una cobertura del 70% de statements (sentencias), functions (funciones), lines (líneas), y branches
 * Tiene un README.md con la siguente:
 - Definición del producto clara e informativa
 -  Historias de usuario
 -  Un Diseño de la Interfaz de Usuaria (prototipo de alta fidelidad)
 -  El listado de problemas que detectaste a través de tests de usabilidad en el README.md
* Tiene un UI que cumple las funcionalidades:
 -  Muestra lista con datos y/o indicadores
 -  Permite ordenar data por uno o más campos (asc y desc)
 -  Permite filtrar data con base en una condición
 -  Permite limpiar los filtros con un botón
 -  Es responsive
```
Y te sugerimos responder las siguientes preguntas:
```
¿Tu proyecto cumple los criterios mínimos de aceptación al ejecutar npm run test:oas?
¿Tu proyecto cumple las pruebas unitarias al ejecutar npm run test?
¿Tu proyecto cumple las pruebas end to end al ejecutar npm run test:e2e?
¿Tu proyecto está libre de errores de eslint al ejecutar npm run test?

Recuerda que estas preguntas pueden contribuir a una sesión de retroalimentación más efectiva y beneficiosa en tu proceso de aprendizaje. Si tienes dudas sobre estos puntos puedes consultar con algún coach, ¡Ellos te podrán orientar de mejor manera!

Importante: Antes de tener un ProjectFeedback debes realizar la autoevaluación de objetivos de aprendizaje y life skills desde tu dashboard de estudiante.
```
Creo el objetivo es enconrar una balanze entre comunicar requisitos pero a misma vez no frenar evaluaciones/conversaciones sobre algunas tests o OAs no cumplido.

**Comment by Davichobits** [comment]
## En el readme de Text Analyzer dice:

_6. Criterios de aceptación mínimos del proyecto_

_Pruebas unitarias (unit tests)_

* [ ] _Se pasan todas las pruebas unitarias._

_7. Pruebas_
_Este proyecto cuenta con 3 conjuntos de pruebas que te ayudarán a conocer si cumples los criterios mínimos de aceptación._

_9. Consideraciones para pedir tu Project Feedback_
_Antes de agendar tu Project Feedback con un coach, asegúrate que tu proyecto:_

* [ ] _Cumple con todos los criterios mínimos de aceptación al ejecutar npm run test:oas_
* [ ] _Cumple con todas las pruebas unitarias al ejecutar npm run test_
* [ ] _Cumple con todas las pruebas end to end al ejecutar npm run test:e2e_
* [ ] _Esta libre de errores de eslint al ejecutar npm run test_
* [ ] _Está subido a GitHub._
* [ ] _Esta desplegado en GitHub Pages._
* [ ] _Tiene un README con la definición del producto._

## En el proyecto de dataverse se tiene:

_10. Consideraciones para pedir tu Project Feedback_

_Antes de agendar tu Project Feedback con un coach, asegúrate que tu proyecto:_

* [ ] _Cumple con todos los criterios mínimos de aceptación al ejecutar `npm run test:oas`_
* [ ] _Cumple con todas las pruebas _end to end_ al ejecutar `npm run test:e2e`_
* [ ] _Cumple con todas las pruebas unitarias al ejecutar `npm run test` y
  que tienen una cobertura del 70% de _statements_ (_sentencias_),
  _functions_ (_funciones_), _lines_ (_líneas_), y _branches__
  
## Mi opinión

* A mi parecer el hecho de tener un checkbox al inicio da la impresión de que solo hay dos opciones: "se cumple" o "no se cumple" y por eso al no tener todo al 100% no piden el PF
* _"Cumple con todos"_ también es una frase que me parece muy estricta. Podría ser _"Cumple con la mayoría"_ ó  _"Cumple con el 70% de"_ así como se hace con la cobertura

En la línea que dice: _Este proyecto cuenta con 3 conjuntos de pruebas que te ayudarán a conocer si cumples los criterios mínimos de aceptación._

Se podría poner una nota al final como: "Recuerda que no es necesario tener todos los test al 100% con que cumplas la mayoría puedes pedir ya Project Feedback"
