### ISSUE TITLE
version minima de node en Text Analyzer y Dataverse

### ISSUE THREAD

**Issue by unjust** [Laboratoria/curriculum#1647]
DEV012 comenta que algunas estudiantes no pueden correr los tests en playwright por la version de node

https://github.com/Laboratoria/curriculum/issues/1632#issuecomment-1804666041
https://github.com/Laboratoria/curriculum/issues/1631

hay que cambiar algo en las dependencias o package json de estes proyectos?
o comunicar mejor la version minima en bootcamp?

**Comment by Davichobits** [comment]
Yo propondría comunicar mejor la versión a utilizar de node.

Puede ser un apartado donde se explique como instalar node o en caso de ya tenerlo instalado de verificar su versión. Y recomendar actualizarla en caso de que no sea la versión actual.

**Comment by unjust** [comment]
@marianaLz tenemos un lugar en Coda de estudiantes donde podemos recomendar el version de node?

**Comment by marianaLz** [comment]
hola! creo que en CODA aún no lo tenemos, pero puedo revisar y llevarme la documentación

**Comment by unjust** [comment]
Decidimos: Recomendamos 18, pero con minimo 16 si sea necesario.
