### ISSUE TITLE
npm run changelog gives error with git describe

### ISSUE THREAD

**Issue by unjust** [Laboratoria/curriculum#1656]
Haciendo el comando tiene este error
```
> curriculum@7.3.0 changelog
> git log $(git describe --tags --abbrev=0)..HEAD --oneline --format="* %h %s (%an)"

warning: tag 'v7.3.0' is externally known as 'v3.7.0'
```
porque tuve que renombrar 3.7.0->7.3.0 (pero hice el renombrar antes el push tags entonces no se porque esta quejando)

Por ahora puedes hacer `git log [VERSION]..HEAD --oneline --format="* %h %s (%an)"`

**Comment by mfdebian** [comment]
quizás esto ayude? https://stackoverflow.com/a/32209958/9654976

**Comment by unjust** [comment]
ahora no hay error , quiza porque cambiamos el tag y el tag anterior o es el mismo
