### ISSUE TITLE
Falta etiqueta para grupos de OAs

### ISSUE THREAD

**Issue by diegovelezg** [Laboratoria/curriculum#1657]
Hay algunos grupos de OAs que no tienen un título o etiqueta.
Acá estoy listando los primeros 2 niveles del árbol que son los que creo necesitamos para renderear distinas cosas lo mejor posible. AL menos el 1er nivel no debe poder ser NULL jamás, ¿no?

cc @mfdebian @unjust @lisperaza  @marianaLz 
Mari, para nuestro caso, yo propongo que sea esto lo que listemos. Porque si colapsamos a JS (por ejemplo) nos perdemos de todo el detalle que nos interesa recopilar

<google-sheets-html-origin><style type="text/css"></style>
OA_path | OA_label_ES | OA_label_PT
-- | -- | --
agile-planning |   |  
agile-planning/scope | Definir alcance general |  
agile-planning/tasks | Gestionar tareas |  
agile-planning/workplan | Crear plan de trabajo |  
ai-prompting | AI Prompting | AI Prompting
ai-prompting/few-shot-prompting | Few shot prompting | Few shot prompting
ai-prompting/giving-instructions | Dando Instrucciones | Dando Instruções
ai-prompting/open-ai-api | OpenAI API | OpenAI API
ai-prompting/priming-chatbots | Priming Chatbots | Priming Chatbots
angular | Angular | Angular
angular/components-and-templates | Components & templates | Components & templates
angular/http-client | Uso de HttpClient | Uso de HttpClient
angular/input-output | @Input \| @Output | @Input \| @Output
angular/observables | Creación y uso de Observables. | Criação e uso de Observables
angular/routing | Manejo de rutas | Gerenciamento de rotas
angular/services | Creación y uso de servicios | Criação e uso de serviços
angular/structural-directives | Directivas estructurales (ngIf / ngFor) | Diretivas estruturais (ngIf / ngFor)
angular/styles | Estilos de componentes (ngStyle / ngClass) | Estilos de componentes (ngStyle / ngClass)
auth | Autenticación | Autenticação
auth/jwt | JWT (JSON Web Token) | JWT (JSON Web Token)
auth/password-access-and-storage | Almacenamiento y acceso de contraseñas | Armazenamento e acesso de senhas
browser | Web APIs | Web APIs
browser/dom | DOM (Document Object Model) | DOM (Document Object Model)
browser/fetch | Fetch API | Fetch API
browser/routing | Ruteado (History API, evento hashchange, window.location) | Routing (History API, evento hashchange, window.location)
browser/storage | Browser storage (localStorage, sessionStorage) | Browser storage (localStorage, sessionStorage)
business | Negocio | Negócios
business-understanding |   |  
business-understanding/benchmark | Analizar competidores |  
business-understanding/business-model | Comprender el modelo de negocio |  
business-understanding/goals-and-kpis | Comprender objetivos e indicadores clave |  
business/benchmark | Entender estado del negocio en relación con el mercado local y global | Entendendo a situação do negócio em relação ao mercado local e global
business/goals | Entender y considerar los objetivos del negocio durante el desarrollo del proyecto | Entenda e considere os objetivos do negócio durante o desenvolvimento do projeto
business/metrics | Definir métricas relevantes para validar el cumplimiento de los objetivos del negocio | Definir métricas relevantes para validar a conformidade com os objetivos de negócios
business/model | Entender el modelo de negocio | Entendendo o modelo de negócio
cicd | Integración Continua/Entrega Continua | Integração Contínua/Entrega Contínua
cicd/build-pipelines | Construcción de pipelines (GitHub Actions/CircleCI) | Construção de pipelines (GitHub Actions/CircleCI)
cicd/integration-tests | Pruebas de integración | Testes de integração
cicd/service-deployment | Despliegue de servicios (Heroku/GitHub Pages) | Implantação de serviços (Heroku/GitHub Pages)
cicd/tbd | Aplicación de Trunk-based Development para Integración Continua | Usar Trunk-based Development para Integração Contínua
cicd/test-coverage | Validación de cobertura de pruebas en pipeline | Validação de cobertura de testes em pipeline
communication | Comunicación | Comunicação
communication/case-study | Presentar su proceso de trabajo en un caso de estudio usando herramientas de storytelling | Apresente seu processo de trabalho em um estudo de caso usando ferramentas de storytelling
communication/negotiation | Negociar efectivamente con clientes | Negociando de forma eficaz com os clientes
communication/presentation | Presentar y sustentar propuestas a clientes | Apresentar e apoiar propostas aos clientes
communication/relationship-management | Manejar relaciones con clientes | Gerenciando o Relacionamento com o Cliente
content-design |   |  
content-design/create-content | Crear contenidos |  
content-design/voice-tone | Definir guía de voz y tono |  
css | CSS | CSS
css/box-model | Modelo de caja (box model): borde, margen, padding | Modelo de caixa (box model): borda, margem, preenchimento
css/flexbox | Uso de flexbox en CSS | Uso de flexbox em CSS
css/grid | Uso de CSS Grid Layout | Uso de CSS Grid Layout
css/media-queries | Uso de media queries | Uso de media queries
css/selectors | Uso de selectores de CSS | Uso de seletores de CSS
db | Bases de datos | Bases de dados
db/connection | Conexión | Conexão
db/indexes-constraints | Índices y limitaciones | Índices e limitações
db/modeling | Modelado de datos | Modelagem de dados
design-concept |   |  
design-concept/define-mvp | Definir MVP |  
design-concept/design-references | Buscar inspiración |  
design-concept/ideate | Idear soluciones |  
design-concept/prioritize-ideas | Priorizar ideas |  
design-pitch |   |  
design-pitch/design-feedback | Recolectar feedback de diseño |  
design-pitch/design-presentation | Presentar ante el negocio |  
design-prototype |   |  
design-prototype/advanced-interactions | Utilizar interacciones avanzadas |  
design-prototype/basic-prototypes | Crear prototipos básicos |  
design-prototype/high-fidelity | Crear prototipos en alta fidelidad |  
design-specs |   |  
design-specs/file-organization | Organizar documentos de Figma |  
design-specs/project-documentation | Documentar el proyecto de diseño |  
design-specs/use-cases | Documentar casos de uso |  
design-systems |   |  
design-systems/atomic-design | Implementar Atomic Design |  
design-systems/design-system | Utilizar sistemas de diseño |  
express | Express.js | Express.js
express/middleware | Uso y creación de middleware | Uso e criação de middleware
express/routing | Manejo de rutas | Gerenciamento de rotas
firebase | Firebase | Firebase
firebase/auth | Firebase Auth | Firebase Auth
firebase/firestore | Firestore | Firestore
front-end-web-dev |   |  
front-end-web-dev/components |   |  
front-end-web-dev/state |   |  
html | HTML | HTML
html/semantics | Uso de HTML semántico | Uso de HTML semântico
http | HTTP | HTTP
http/body | Cuerpo (body) | Corpo (body)
http/cors | CORS (Cross-Origin Resource Sharing) | CORS (Cross-Origin Resource Sharing)
http/headers | Cabeceras (headers) | Cabeçalhos (headers)
http/json | Encodings y JSON | Encodings e JSON
http/request-response | Consulta o petición (request) y respuesta (response). | Consulta ou solicitação (request) e resposta (response).
http/status-codes | Códigos de status de HTTP | Códigos de status de HTTP
http/verbs | Verbos HTTP | Verbos HTTP
interaction-design |   |  
interaction-design/information-architecture | Crear la arquitectura de información |  
interaction-design/usability | Utilizar principios de usabilidad |  
interaction-design/user-flows | Crear flujos de usuario |  
interface-design |   |  
interface-design/accesibility | Utilizar principios de accesibilidad |  
interface-design/responsive-design | Implementar diseño responsivo |  
interface-design/visual-design | Crear propuesta de diseño visual |  
java | Java | Java
java/access-modifiers | Modificadores de acesso (public, private, protected) | Modificadores de acesso (public, private, protected)
java/collections | Colecciones | Coleções
java/conditionals | Uso de condicionales | Uso de condicionais
java/data-types | Tipos de data | Tipos de dados
java/hibernate-orm | Hibernate ORM | Hibernate ORM
java/loops | Uso de bucles (Loops) | Uso de loops (Laços)
java/spring-framework | Spring Framework | Spring Framework
java/testing | Testing | Testes
java/variables | Variables | Variáveis
js | JavaScript | JavaScript
js/async |   |  
js/conditionals | Uso de condicionales (if-else, switch, operador ternario, lógica booleana) | Uso de condicionais (if-else, switch, operador ternário, lógica booleana)
js/data-types |   |  
js/expression-vs-statement | Diferenciar entre expresiones (expressions) y sentencias (statements) | Diferença entre expressões (expressions) e declarações (statements)
js/functions | Funciones (params, args, return) | Funções (params, args, return)
js/linting | Uso de linter (ESLINT) | Uso de linter (ESLINT)
js/loops | Uso de bucles/ciclos (while, for, for..of) | Uso de laços (while, for, for..of)
js/modules |   |  
js/recursion | Recursión o recursividad | Recursão
js/semantics | Uso de identificadores descriptivos (Nomenclatura y Semántica) | Uso de identificadores descritivos (Nomenclatura e Semântica)
js/testing |   |  
js/variables | Variables (declaración, asignación, ámbito) | Variáveis (declaração, atribuição, escopo)
mongodb | MongoDB | MongoDB
mongodb/crud | Operaciones CRUD (Create-Read-Update-Delete) | Operações CRUD (Create-Read-Update-Delete)
mongodb/dump-restore | Respaldo y restauración (backup/restore) | Recuperação e restauração (backup/restore)
mongodb/schemas | Modelos y esquemas de datos | Modelos e esquemas de dados
mysql | MySQL | MySQL
mysql/data-types | Tipos de datos | Tipos de dados
mysql/dump-restore | Respaldo y restauración (backup/restore) | Backup e restauração (backup/restore)
mysql/indexes | Índices | Índices
mysql/mysql | Cliente de terminal mysql | Cliente de terminal mysql
node | Node.js | Node.js
node/filesystem | File system (fs, path) | File system (fs, path)
node/npm-install | Instalar y usar módulos con npm | Instalar e usar módulos com npm
node/npm-scripts | Configuración de npm-scripts | Configuração do npm-scripts
node/package.json | Configuración de package.json | Configuração do package.json
node/process | process (env, argv, stdin-stdout-stderr, exit-code) | process (env, argv, stdin-stdout-stderr, exit-code)
object-oriented-programming | Programación Orientada a Objetos (OOP) | Programação Orientada a Objetos (POO)
object-oriented-programming/abstraction | Abstracción | Abstração
object-oriented-programming/attributes | Atributos | Atributos
object-oriented-programming/classes | Clases | Classes
object-oriented-programming/composition | Composición | Composição
object-oriented-programming/constructors | Constructores | Construtores
object-oriented-programming/encapsulation | Encapsulamiento | Encapsulamento
object-oriented-programming/inheritance | Herencia (super, extends, override) | Herança (super, extends, override)
object-oriented-programming/interfaces | Interfaces | Interfaces
object-oriented-programming/methods | Métodos | Métodos
object-oriented-programming/objects | Objetos | Objetos
object-oriented-programming/unified-model-language | Lenguaje de Modelado Unificado (UML, class diagrams) | Linguagem de Modelagem Unificada (UML, diagramas de classe)
php | PHP | PHP
php/control-structures | Estructuras de control en PHP (if, else, elseif, else if, while, do while, for) | Estruturas de controle em PHP (if, else, elseif, else if, while, do while, for)
php/data-types |   |  
php/functions | Funciones en PHP (params, args, return) | Funções em PHP (params, args, return)
php/package-management |   |  
php/testing |   |  
php/variables | Variables en PHP (declaración, asignación, ámbito) | Variáveis em PHP (declaração, atribuição, escopo)
planning | Planificación | Planejamento
planning/monitor | Organizar y dar seguimiento a actividades a desarrollarse durante el proyecto | Organizar e monitorar as atividades a serem desenvolvidas durante o projeto
planning/prioritization | Priorizar actividades a desarrollarse durante el proyecto | Priorizar as atividades a serem desenvolvidas durante o projeto
planning/tools | Elegir las herramientas y métodos a utilizar de acuerdo a las necesidades  del proyecto | Escolha as ferramentas e métodos a utilizar de acordo com as necessidades do projeto
postgres | PostgreSQL | PostgreSQL
postgres/data-types | Tipos de datos | Tipos de dados
postgres/dump-restore | Respaldo y restauración (backup/restore) | Backup e restauração (backup/restore)
postgres/indexes | Índices | Índices
postgres/psql | Cliente de terminal psql | Cliente de terminal psql
product-design | Diseño de producto | Design de produto
product-design/accessibility | Diseñar producto o servicio siguiendo mejores prácticas de accesibilidad | Projetar produto ou serviço seguindo as melhores práticas de acessibilidade
product-design/component-organization | Crear y utilizar componentes reutilizables | Criar e usar componentes reutilizáveis
product-design/content | Identificar y priorizar contenidos relevantes y necesarios para el producto | Identificar e priorizar conteúdos relevantes e necessários para o produto
product-design/documentation | Documentar los distintos componentes de UI y sus casos de uso | Documentar os vários componentes da interface do usuário e seus casos de uso
product-design/fidelity | Diseñar en distintos niveles de fidelidad | Design em diferentes níveis de fidelidade
product-design/interactivity | Crear prototipos de alta fidelidad que incluyan interacciones | Criar protótipos para obter feedback e iterar
product-design/project-organization | Nombrar, organizar, agrupar las capas (layers) del diseño siguiendo buenas prácticas | Nomear, organizar, agrupar as camadas (layers) do design seguindo boas práticas
product-design/usability | Diseñar producto o servicio siguiendo mejores prácticas de usabilidad | Projetar produto ou serviço seguindo as melhores práticas de usabilidade
product-design/user-flows | Priorizar y proponer flujos de usuaria que les ayuden a conseguir sus objetivos con el producto | Priorizar e propor fluxos de usuários que os ajudem a atingir seus objetivos com o produto
product-design/visual-design | Seguir los principios básicos de diseño visual | Aplicar os princípios de desenho visual (contraste, alinhamento, hierarquia)
react | React | React
react/components | Componentes y propiedades (props) | Componentes e propriedades (props)
react/conditional-rendering | Renderizado condicional | Renderização condicional
react/css-modules | CSS modules | CSS modules
react/events | Manejo de eventos | Manipulação de eventos
react/hooks | Hooks | Hooks
react/jsx | JSX | JSX
react/lifting-up-state | Elevación de estado | Elevação de estado
react/lists-and-keys | Listas y keys | Listas e keys
react/routing | React Router | React Router
research | Investigación | Pesquisa
research/adaptation | Adaptar plan de investigación de acuerdo a resultados obtenidos | Adaptar o plano de pesquisa de acordo com os resultados obtidos
research/analysis |   |  
research/cuantitative-data | Recopilar, analizar e interpretar data cuantitativa | Coletar, analisar e interpretar dados quantitativos
research/documentation | Documentar entrevistas y testeos | Documentar entrevistas e testes
research/guidelines | Crear y probar guía de actividades de investigación | Criar e testar guia de atividades de pesquisa
research/interview | Realizar entrevistas con usuarias empáticas y sin sesgos | Conduzindo entrevistas com usuários empáticos e imparciais
research/planning | Planificar investigación basada en las necesidades del proyecto | Planejamento da pesquisa com base nas necessidades do projeto
research/qualitative |   |  
research/quantitative |   |  
research/sources | Identificar y revisar distintas fuentes de información e inspiración relevantes para el proyecto | Identificar e revisar diferentes fontes de informação e inspiração relevantes para o projeto
research/support | Elegir y sustentar el # usuarias que participan en actividades de investigación | Escolha e apoie os # usuários que participam de atividades de pesquisa
research/test | Planear y ejecutar testeos de usabilidad de prototipos en distintos niveles de fidelidad | Planejar e executar testes de usabilidade
scm | Control de Versiones (Git y GitHub) | Controle de Versões (Git e GitHub)
scm/git |   |  
scm/github |   |  
slack | Slack | Slack
slack/slash-commands | Slash commands de Slack | Slash commands de Slack
socket-io | Socket.IO | Socket.IO
socket-io/client | Cliente JavaScript de Socket.io | Cliente JavaScript de Socket.io
socket-io/server | Servidor de Node.js de Socket.io | Servidor de Node.js de Socket.io
sql | SQL | SQL
sql/crud | Operaciones CRUD (Create-Read-Update-Delete) | Operações CRUD (Create-Read-Update-Delete)
sql/drop | Borrado de tablas o bases de datos enteras con DROP | Exclusão de tabelas ou bancos de dados inteiros com DROP
sql/tables | Creación y modificación de tablas | Criação e modificação de tabelas
synthesis | Síntesis | Síntese
synthesis/feature-prioritization | Priorizar las posibles soluciones que aporten más valor al proyecto, basándose en los objetivos del proyecto y las necesidades de los usuarios | Priorizar as possíveis soluções que agregam mais valor ao projeto, com base nos objetivos do projeto e nas necessidades dos usuários
synthesis/features | Definir funcionalidades del producto | Definir características do produto
synthesis/ideation | Generar múltiples ideas de solución al reto del proyecto | Gerar várias ideias de soluções para o desafio do projeto
synthesis/insights | Diferenciar entre observaciones, hallazagos e insights | Diferenciar entre observações, descobertas e insights
synthesis/mapping | Usar herramientas de síntesis para mapear las experiencias de los usuarios | Usando ferramentas de síntese para mapear as experiências do usuário
synthesis/patterns | Encontrar patrones en los resultados de la investigación | Encontrando padrões nos resultados da pesquisa
synthesis/weighing | Distinguir observaciones, data y/o respuestas que aportan valor al proyecto | Distinguir observações, dados e/ou respostas que agregam valor ao projeto
typescript |   |  
typescript/basic-types |   |  
typescript/classes | Clases | Classes
typescript/decorators | Decoradores | Decoradores
typescript/narrowing | Narrowing | Narrowing
usability-analysis |   |  
usability-analysis/heuristic-analysis | Realizar análisis heurísticos |  
usability-analysis/moderated-testing | Realizar pruebas moderadas |  
usability-analysis/non-moderated-testing | Realizar pruebas no-moderadas |  
user-centricity | Centrado en el usuario | Centrado no usuário
user-centricity/centricity | Diseñar y desarrollar un producto o servicio poniendo a las usuarias en el centro | Desenhar e desenvolver um produto ou serviço colocando as usuárias no centro
user-centricity/prioritization | Identificar y priorizar usuarias relevantes para el proyecto | Identificar e priorizar usuários relevantes para o projeto
user-centricity/user-oriented | Involucrar usuarias y tomar en cuenta sus necesidades a lo largo de todo el proceso de diseño | Envolva os usuários e leve em consideração suas necessidades durante todo o processo de design
vue | Vue | Vue
vue/classes-and-styles | Clases y Estilos | Classes e Estilos
vue/components | Uso y creación de componentes | Uso e criação de componentes
vue/computed-props-and-observers | Propiedades Computadas y Observadores | Dados Computados e Observadores
vue/data-and-methods | Datos y métodos | Dados e métodos
vue/directives | Directivas (v-bind \| v-model) | Diretivas (v-bind \| v-model)
vue/events | Eventos (v-on) | Eventos (v-on)
vue/instance | Instancia de Vue.js | Instância de Vue.js
vue/iteration | Iteración (v-for) | Iteração (v-for)
vue/props | Props | Props
vue/routing | Routing | Routing
webops | WebOps | WebOps
webops/cloud-functions | Cloud Functions | Cloud Functions
webops/docker-compose | Docker compose | Docker compose
webops/docker-containers | Contenedores (Docker) | Containers (Docker)
webops/env-vars | Variables de entorno | Variáveis de ambiente
wordpress | WordPress | WordPress
wordpress/plugin-development |   |

**Comment by unjust** [comment]
Puedo ver las OAs de web-dev. Me parece muchas de esos son OAs de UX. 
@lisperaza puede ayudar con ellos?

**Comment by lisperaza** [comment]
Hola, estos son los títulos para los grupos de OAs de la currícula actual de UXD:

agile-planning = Planificación ágil
business-understanding = Entendimiento del negocio
research/planning = Planteamiento de la investigación
research/qualitative = Técnicas cualitativas (exploratorio)
research/quantitative = Técnicas cuantitativas (analítico)
research/analysis = Análisis de la investigación
design-concept = Concepto de diseño
interaction-design = Diseño de interacción
content-design = Diseño de contenido
interface-design = Diseño de interfaces
design-prototype = Prototipado
usability-analysis = Análisis de usabilidad
design-pitch = Pitch de diseño
design-specs = Especificaciones de diseño
design-systems = Sistemas y librerías de diseño

**Comment by lisperaza** [comment]
Existen varios OAs de UX que pertenecen a la curricula anterior (de mi parte se pueden eliminar pero no sé si alguien más lo usa para algo) o relacionados con el track de WD.

Además, por nomenclatura se anidaron todos los OAs relacionados con research, pero en la práctica son metas de aprendizaje (categorías, grupos de OAs) independientes entre sí, es decir, una estudiante puede ejecutar un análisis de investigación sin realizar los otros 3 bloques:

research/planning = Planteamiento de la investigación
research/qualitative = Técnicas cualitativas (exploratorio)
research/quantitative = Técnicas cuantitativas (analítico)
research/analysis = Análisis de la investigación

Para mí es mucho mejor si mantenemos solamente 2 niveles de anidación ya que al llenar los forms se vuelve complejo diferenciar OAs de una meta de aprendizaje vs la otra, pero entiendo que les quede más práctico unirlos.

**Comment by marianaLz** [comment]
@diegovelezg en el caso de UX voy a poner estos, está bien para la recopilación de la data, vdd?

agile-planning = Planificación ágil
business-understanding = Entendimiento del negocio
research/planning = Planteamiento de la investigación
research/qualitative = Técnicas cualitativas (exploratorio)
research/quantitative = Técnicas cuantitativas (analítico)
research/analysis = Análisis de la investigación
design-concept = Concepto de diseño
interaction-design = Diseño de interacción
content-design = Diseño de contenido
interface-design = Diseño de interfaces
design-prototype = Prototipado
usability-analysis = Análisis de usabilidad
design-pitch = Pitch de diseño
design-specs = Especificaciones de diseño
design-systems = Sistemas y librerías de diseño

Pregunta: uso, por ejemplo, `design-systems` y no `Sistemas y librerías de diseño`, cierto?

**Comment by unjust** [comment]
Como @lisperaza dice 

> Existen varios OAs de UX que pertenecen a la curricula anterior (de mi parte se pueden eliminar pero no sé si alguien más lo usa para algo) o relacionados con el track de WD.

Podemos eliminar lo que no usamos? @diegovelezg O deberiamos quedar con ellos y poner titulos en todos.
