### ISSUE TITLE
OAs Fleet Management Software API 

### ISSUE THREAD

**Issue by cros410** [Laboratoria/curriculum#1663]
Actualizar los OAs del proyecto para solo quedarnos e incluir los que consideramos indispensables 

```yml
  - java/spring-framework/beans
  - java/spring-framework/inversion-of-control
  - java/spring-framework/spring-boot
  - java/spring-framework/servlets
```
- Eliminar algunos conceptos Core
- Eliminar servlets
- Agregar dependency injection

***

```yml
- sql/tables
- db/modeling
- db/connection
- db/indexes-constraints
- postgres/data-types
 ```
 
sql/tables: Crear las tablas para cargar
db/modeling: Identificar que campos debe tener cada tabla
db/connection: Conectarse desde un cliente para ver la BD
db/indexes-constraints: Agregar las relaciones y caracteristicas ( PF, PK )
postgres/data-types: Identificar la diferencia de los tipos de datos con los de Java

**Comment by ssinuco** [comment]
OAs definitivos

  - java/spring-framework/beans
  - java/spring-framework/dependency-injection
  - java/spring-framework/spring-boot
  - java/spring-framework/spring-boot

OAs definitivos

db:
  - indexes-constraints

sql:
  - tables

postgres:
  - data-types
