### ISSUE TITLE
Cambia los sprints recomendados en Dataverse README

### ISSUE THREAD

**Issue by unjust** [Laboratoria/curriculum#1667]
Verifica con @marianaLz la cantidad. Creo 4 - 6 sprints.

**Comment by marianaLz** [comment]
Sí, en este momento son 4 a 6 sprints
se va a cambiar? o vamos a esperar los cambios en el readme, para ver si dejamos en 3 a 5 sprints y con los cambios se logra en ese tiempo?

**Comment by ChristianRL23** [comment]
¿Entonces el readme de Dataverse se cambiaría a 4 - 6 sprints? Actualmente dice de 3 a 4 sprints.
![image](https://github.com/Laboratoria/curriculum/assets/87323279/57a5c702-bfb1-49d3-a9a5-1eeb3c5cf8bf)

**Comment by marianaLz** [comment]
1. Con la data recopilada de DEV012 tenemos de 4 a 6 sprints
2. @unjust lo cambiamos o dejamos 3 a 5 con los cambios que harás?
3. el tiempo para generar el dataset de 1 sprint me parece excesivo, es algo que les debería tomar horas, no días

**Comment by unjust** [comment]
Opto por 4-5 sprints y ver con los cambios  donde estamos.

Quiza 1 sprint es mucho pero debe hacerlo con otras cosas en parallelo (prototipo de alta, arma el noilerplate), podemos decir eso en la guia de coaches y ver si necesitamos cambiar el lenguaje de readme.

**Comment by marianaLz** [comment]
de acuerdo con los sprints

creo que sí debemos darle una vuelta al lenguaje porque parece que tienen todo un sprint solo para eso
