### ISSUE TITLE
Text-analyzer data-testid es presentada como html semantica pero tests pasan igual sin eso

### ISSUE THREAD

**Issue by moniyama** [Laboratoria/curriculum#1668]
Hola, 
Algunas estudiantes de SAP012 han identificado alguns errores en los tests del proyecto 01-text-analyzer:
- No hay en atributo `data-testid` pero los tests de oa-html se passa normal
- Se pide que hay un Event Listener para un `input` pero es pedido que se use un `textarea` en readme

@marianaLz te menciono solo para FYI

![10C03566-ADC6-46C9-9147-F4534511C805](https://github.com/Laboratoria/curriculum/assets/52083679/121df09a-e350-4b7a-a73b-7caf507cbe7a)
![Screenshot 2023-12-11 093740](https://github.com/Laboratoria/curriculum/assets/52083679/12a69d98-84cb-48fb-bdf6-324208431259)

**Comment by unjust** [comment]
@Davichobits Este es lo de cohort https://github.com/Laboratoria/SAP012-text-analyzer

**Comment by Davichobits** [comment]
Hola @moniyama ten en cuenta que los test de `data-testid` no son parte de HTML semántico (en el readme están detallados ahí y es algo que hay corregir) Pero si corres los test 2e2 ahí si se van a testear esos atributos. Voy a crear un PR corrigiendo la redacción del readme.

**Comment by Davichobits** [comment]
@moniyama con respecto a esto no me queda claro el problema:

`Se pide que hay un Event Listener para un input pero es pedido que se use un textarea en readme`

El test es el siguiente:

```js
describe('Manejo de eventos del DOM', () => {
  it('Se registra un Event Listener para el evento "input"', () => {
    expect(
      addEventListenerCalls.some((node) => node.arguments[0].value === "input")
    ).toBeTruthy();
  });

  it('Se registra un Event Listener para el evento "click"', () => {
    expect(
      addEventListenerCalls.some((node) => node.arguments[0].value === "click")
    ).toBeTruthy();
  });

});
```

Se está testeando que se escuche un evento "input". Una etiqueta `textarea` puede tener un evento "input" que se activa cuando la usuaria ingresa algún texto en el `textarea`. Hay algo que no estoy viendo?

**Comment by moniyama** [comment]
ooh perfecto! gracias @Davichobits! 
Entonces la idea es que no tenga esos tests en `npm run:oas-html` ya q no hacen parte del oa de html semantico, y esa info se queda en otra parte del criterio para coger en los tests e2e, certo?

**Comment by moniyama** [comment]
oooh ES VERDAD sobre INPUT! Creo q he leído equivocadamente por la lengua!

Pero, entonces.. en la verdad, eso deberia ser `keyup`, no? o el evento de keyup ya está "incluido" en eso?

**Comment by Davichobits** [comment]
La verdad cualquiera de los dos funciona para este caso ya sea `input` o `keyup`. 

Personalmente me gusta más `input` porque abarca más posibilidades de ingreso de datos y uso `keyup` cuando quiero escuchar específicamente ese evento por algo muy particular. @unjust que opinas tu?

> oooh ES VERDAD sobre INPUT! Creo q he leído equivocadamente por la lengua!
> 
> Pero, entonces.. en la verdad, eso deberia ser `keyup`, no? o el evento de keyup ya está "incluido" en eso?

**Comment by moniyama** [comment]
creo que entedi la confusión acá @Davichobits !

en el README en español si pide el evento de `input`, pero en el README em pt-BR si pide el evento de `keyup`

![image](https://github.com/Laboratoria/curriculum/assets/52083679/d09c4f51-623a-4693-aa04-42cc1818f1d4)
![image](https://github.com/Laboratoria/curriculum/assets/52083679/4dbaf1fa-0282-468e-bf0d-c637d5f92a52)

**Comment by unjust** [comment]
@Davichobits  y @moniyama - el evento deberria ser `input` - arreglamos eso en un PR antes https://github.com/Laboratoria/curriculum/issues/1494

> La verdad cualquiera de los dos funciona para este caso ya sea `input` o `keyup`.
> 
> Personalmente me gusta más `input` porque abarca más posibilidades de ingreso de datos y uso `keyup` cuando quiero escuchar específicamente ese evento por algo muy particular. @unjust que opinas tu?
> 
> > oooh ES VERDAD sobre INPUT! Creo q he leído equivocadamente por la lengua!
> > Pero, entonces.. en la verdad, eso deberia ser `keyup`, no? o el evento de keyup ya está "incluido" en eso?

**Comment by unjust** [comment]
Addressed in #1673
