### ISSUE TITLE
Dataverse Chat en menos sprints

### ISSUE THREAD

**Issue by unjust** [Laboratoria/curriculum#1685]
Para ayudar las estudiantes (y coaches) cumplir el proyecto en menos sprints pensamos en ideas:

- [x] #1686
- [ ] incluimos los tests (o al menos el bolierplate) para el router
- [ ] reforzar que los tests puede ser en parallelo para evitar un sprint para HU un sprint para test etc

**Comment by jmontes50** [comment]
Adicional a esto teníamos unas preguntas en mente:

Los test de rutas deberían estar en el primer sprint?, consideramos que se pueden implementar en ese primer sprint pero que según hagan cambios a sus vistas los tests también tendrían que cambiar.

En la implementación vimos que se ofuscaba la API KEY, esto se consideraría como un requisito o es algo añadido? en el readme de DVC no encontramos mencionado que se tenga que ofuscar. 

Tenemos un PR Draft https://github.com/Laboratoria/curriculum/pull/1700 pero no hemos considerado esas dudas

**Comment by marianaLz** [comment]
Pienso que los tests sí pueden estar desde sprint 1, pero creen que les ayude o les frustre tener que estarlos cambiando?

**Comment by moniyama** [comment]
solo quería agregar acá sobre los tests en los milestones:
- los tests de router están solo en guide, topic 10, y no es mencionado en los milestones y puede ser facilmente olvidado. 
- los tests async de las funciones de open-ai está solo al final de milestone 4 (que es la funcionalidad de panel). Creo que se vamos a pensar en la possibilidad de una version más corta, eso debería estar al final del milestone 3 (chat individual)
- no he visto sobre los testes de view en ningun milestone. Está sendo pedido en algun lugar?
