### ISSUE TITLE
Proyecto implementacion Guess The Number en Python

### ISSUE THREAD

**Issue by unjust** [Laboratoria/curriculum#1689]
https://github.com/Laboratoria/impl-guess-the-number-py

Analizar el proyecto [guess the number](https://github.com/Laboratoria/curriculum/tree/main/projects/05-guess-the-number) y definir estrategia de implementación intentando de NO usar modulos externos
* repo en lab `impl-guess-the-number-py`
* usamos issues y milestones
* code reviews
* incluídos tests 

una version no orientada a objetos - y porque puede ser un proyecto bien sencillo, agregamos extensions para OOP, inteligencia artificial, web app?

**Comment by icarito** [comment]
Hay dos implementaciones iniciales hechas por ChatGPT, probadas.
Una "pitónica" y otra orientada a objetos: https://github.com/icarito/python-labo-implementations

**Comment by unjust** [comment]
https://github.com/Laboratoria/impl-guess-the-number-py
