### ISSUE TITLE
Proyecto Guess The Number requisitos de Python (Readme, OAs)

### ISSUE THREAD

**Issue by unjust** [Laboratoria/curriculum#1690]
Depends on #1689 

Necesitamos editar esta readme un poco mas para ser agnostico de java y incluir docs de java y python como links.

Puede tener partes:
* Preambulo en general.
* Dos readmes extra para cada stack (java y python)
* Lo de python tiene partes de recursos, que un version no necesita clases
* hacker edition con IA para el compu
* opcional extension con clases si - piensa en usar framework como django para siguiente proyecto o ORM
* version en portugues

Estructura:
``` yaml
05-guess-the-number
     - README.md        # preambulo, resumen, objetivos, consideraciones generales, stack de technologias/hitos
     - README.pt.md
     - docs/
       - README-java.md    # consideraciones tecnicos, hitos java, recomendaciones(corta pega de readme anterior)
       - README-java.pt.md
       - README-python.md # consideraciones tecnicos, hitos de python (sin hito 3 corta pega de readme anterior)
       - README-python.pt.md
```

**Comment by ssinuco** [comment]
cuando se tengan el README y OAS, entonces incluir la ruta en el bootcamp book de estudiantes https://coda.io/d/Bootcamp-Book_dUrlCH0OK3j/Rutas-de-especializacion_suMRn#_lu6XC
