### ISSUE TITLE
Proyecto Fleet Management API requisitos de Python (Readme, OAs)

### ISSUE THREAD

**Issue by unjust** [Laboratoria/curriculum#1691]
Depends on #1688

**Comment by icarito** [comment]
Hay una implementación por ChatGPT en Flask y SQLAlquemy sobre Postgresql:
https://github.com/icarito/python-labo-implementations

**Comment by ssinuco** [comment]
cuando se tengan el README y OAS, entonces incluir la ruta en el bootcamp book de estudiantes https://coda.io/d/Bootcamp-Book_dUrlCH0OK3j/Rutas-de-especializacion_suMRn#_lu6XC

**Comment by unjust** [comment]
Algunos frases para cambiar/ caligicar:

"Puedes crear una tabla en PostgreSQL usando [SQL](https://www.postgresqltutorial.com/postgresql-create-table/)." si no estas usando ORM

"El código endpoint debe estar cargado en un repositorio de Github."

**Comment by unjust** [comment]
Decimos que location devuelva "timestamp" y no date y time aparte
