### ISSUE TITLE
Actualización de OAs UXD

### ISSUE THREAD

**Issue by lisperaza** [Laboratoria/curriculum#1701]
Hola team! Necesitamos actualizar la currícula de UXD con los siguientes cambios:

- [x] #1706
--
- [x] #1708
- [ ] #1715 
--
- [ ] #1711
- [ ] https://github.com/Laboratoria/curriculum/issues/1707

**Comment by lisperaza** [comment]
Todos estos cambios necesitamos que se reflejen en el formulario de OAs (autoevaluación, peer, coach) para el próximo Project Feedback de la generación actual UXD007. Terminan el proyecto #1 (design detectives) el **miércoles 24 de enero**

Gracias!

**Comment by unjust** [comment]
@lisperaza viendo Design Detectives OAs https://github.com/Laboratoria/curriculum/blob/main/projects/01-design-detectives/project.yml creo que los puntos que necesitamos arreglar antes de la fecha son de research no? (numero uno en la lista aqui)

**Comment by lisperaza** [comment]
Si, ese punto es el que más afecta y agregar el último OA de Inteligencia Artificial:

design-pitch:
- ai-presentations

title: Apoyarse en herramientas de IA para presentar propuestas
description: Utilizar herramientas de inteligencia artificial (IA) para crear el story-telling y/o presentación ante stakeholders

**Comment by lisperaza** [comment]
Acabo de caer en cuenta que también hay que actualizar el proyecto Design Detectives para incluir este OA de Inteligencia Artificial y eliminar/agregar otros OAs que ya existen pero no estaban como parte de este primer proyecto.

Estos son los OAs que debería tener. Resalté los cambios en bold:

track: ux
learningObjectives:

- **agile-planning/workplan (added)**
- agile-planning/tasks
- business-understanding/benchmark
- **user-research/research-planning/research-plan (added)**
- **user-research/research-planning/desk-research (added)**
- **user-research/research-planning/research-sample (added)**
- **user-research/research-planning/participants (added)**
- **user-research/quantitative/user-surveys (added)**
- **user-research/research-analysis/process-information (added)**
- **user-research/research-analysis/identify-patterns (added)**
- user-research/research-analysis/synthesize-results
- ~~**design-concept/define-mvp (deleted)**~~
- design-concept/design-references
- design-concept/ideate
- design-concept/prioritize-ideas
- interaction-design/user-flows
- interaction-design/usability
- ~~**interaction-design/information-architecture (deleted)**~~
- interface-design/visual-design
- ~~**interface-design/accesibility (deleted)**~~
- design-prototype/basic-prototypes
- **design-prototype/high-fidelity (added)**
- usability-analysis/moderated-testing
- usability-analysis/heuristic-analysis
- design-pitch/design-feedback
- design-pitch/design-presentation
- **design-pitch/ai-presentations (new)**
- design-specs/file-organization
- ~~**design-specs/use-cases (deleted)**~~
- design-specs/project-documentation

**Comment by unjust** [comment]
@lisperaza 
los objetivos de `research-planning` `research-analysis` etc no estan bajo de `user-research`
como [cambiamos en este PR (que aprobaste)](https://github.com/Laboratoria/curriculum/pull/1709/files#diff-10b256d70ed906d0018e53f579eac3c5f2bdd33ba5509a5041009eb112e6d63bR344-R362).

son

`research-planning` 
`research-qualitative`
`research-quantitative`
`research-analysis`

**Comment by lisperaza** [comment]
No, así está perfecto!
