### ISSUE TITLE
Actualizar titles y descriptions de  OAs UX

### ISSUE THREAD

**Issue by unjust** [Laboratoria/curriculum#1711]
goals-and-kpis:
title: Comprender objetivos e indicadores de negocio

analytical-techniques:
description: Explorar herramientas de monitoreo de acciones de usuarios (mapa de calor, analytics, card sorting cerrado, etc.)

experience-mapping:
title: Visualizar la experiencia del usuario
description: Sintetizar la información obtenida de los usuarios mediante alguna técnica de documentación para UX (user journey map, mapa de empatía, etc.)

responsive-design:
description: Crear diseños independientes que se adapten a diferentes dispositivos, utilizando principios de responsive design

voice-tone:
title: Crear guía de voz y tono
description: Definir características clave de la voz y el tono para micro-contenido UX según la marca

micro-content: (changed from create-content to micro-content)
title: Proponer micro-contenido para UX
description: Crear o mejorar el micro-contenido (botones, instrucciones, etiquetas, etc.) en la interfaz para mejorar la usabilidad

visual-content: (new)
title: Definir contenido visual para UX
description: Proponer el lenguaje visual de las imágenes, iconos e ilustraciones para mejorar la experiencia del usuario

design-presentation:
title: Presentar ante stakeholders
description: Presentar ante negocio y/o coaches los resultados de investigación, propuestas y proceso de diseño utilizando principios de "story-telling"

use-cases:
title: Documentar componentes

**Comment by unjust** [comment]
@lisperaza seria bueno esperar en eso porque vamos a necesitar actualizar todo los typeforms que usan. mejor esperamos por project feedbacks en bootcamp.la

**Comment by lisperaza** [comment]
Oky, estoy de acuerdo!
