### ISSUE TITLE
csharp/.net Definimos objetivos de aprendizaje

### ISSUE THREAD

**Issue by unjust** [Laboratoria/curriculum#1720]
En los archivos de https://github.com/Laboratoria/curriculum/tree/main/learning-objectives
tenemos que agregar OAs de chsharp a `data.yml`
y de ahi traducciones de titulos y recursos en `intl/es.yml` y `intl/pt.yml`

Primero empezamos con la estructura en `data.yml` y despues estamos en acuerdo, agregamos titulos y recursos;

Los "llaves" de Objetivos de aprendizaje son 
- `minuscula`
- `kebab-case-syntax`
- en `data.yml`, tiene su hierarchia por la nivel de indentacion 
- y en los traducciones `es` y `pt`  la hierarchia esta escrito en la llave completa

Ejemplo en `data.yaml`
```yaml
browser:
  - dom:
      - selectors
      - events
```

en `es.yml`
- browser:
- browser/dom:
- browser/dom/selectors
- browser/dom/events

**Comment by jmontes50** [comment]
Con @JuanCarlosHM conversabamos y agregamos:

```yml
  - classes
  - objects
```

Porque la implementación en csharp es algo así:

``` cshar´p
class MiClase
{
    // Atributo de la clase
    private string mensaje;

    // Constructor por defecto donde se usa el mismo nombre de la clase
    public MiClase()
    {
        mensaje = "Hola, soy un objeto de MiClase";
    }
}
```

Y pensamos que se podría añadir como OA ya que tiene su manera de implementar clases, lo quitamos y lo dejamos como objetivo de `object-oriented-programming` ? @unjust @JuanCarlosHM @danilolab

**Comment by jmontes50** [comment]
Revise el [repositorio de guess the number de dev011](https://github.com/Laboratoria/DEV011-guess-the-number) y vi que los OA's de OOP aparecen justo debajo, asi que creo que seria mejor retirar clases y objects de csharp como algo especifico, ya que seria confuso que se repita.
