### ISSUE TITLE
Hitos de Dataverse Chat en portugues

### ISSUE THREAD

**Issue by unjust** [Laboratoria/curriculum#1723]
Estamos testando se os marcos ajudarão os alunos #1686
Podemos adicionar traduções em pt e também testar em paralelo.

Estamos probando si hitos va a ayudar las estudiantes #1686 
podemos agregar traducciones en pt y probar tambien en parallelo.

**Comment by moniyama** [comment]
Gracias, Ivy! 
Hablando con la equipo brasil, nos gustó mucho la idea de los hitos y nos gustaría probarlo también! 

Vamos a hacer un workforce para traducirlo y ya aplicarlos para SAP012, así luego hacemos el PR para la curricula
