### ISSUE TITLE
Prep Fleet Management to replace BQ API in Bootcamp

### ISSUE THREAD

**Issue by unjust** [Laboratoria/curriculum#1753]
We want to retire BQ API for a time period and use Fleet Management as the backend project in bootcamp. BQ API was well suited since there was the Client project to provide context for the api endpoints. We want to add/change the following so Fleet Management has the same:

- [x] Add context in each User Story in Fleet Management to contextualize the API to a client's needs
ex. Locations for taxi by date - User needs to see a taxi's locations on a particular date, and the ui presents a field for taxi ids and a date picker. Optionally add images of wireframes or figma to show app
- [x] Create swagger documentation for Fleet Management endpoints to enforce/describe API behavior
- [x] deliver e2e tests for Fleet Management, hopefully language agnostic

We want this done by DEV014

**Comment by merunga** [comment]
Personalmente no estoy tan seguro si queremos q ellas hagan sus tests o si los tests ya vengan en el boilerplate

**Comment by ssinuco** [comment]
Aprovechar para atacar tambien el issue #1675

**Comment by ssinuco** [comment]
![Uploading US2.gif…]()

**Comment by ssinuco** [comment]
![US4](https://github.com/Laboratoria/curriculum/assets/16993732/56e82746-ff9c-4f9e-9e41-b25199658da4)

**Comment by ssinuco** [comment]
![US2](https://github.com/Laboratoria/curriculum/assets/16993732/51da0197-b860-42b8-84e7-732523655f50)

**Comment by ssinuco** [comment]
![US3](https://github.com/Laboratoria/curriculum/assets/16993732/c5e5e3ea-779b-4725-8dbb-892b41e0c740)

**Comment by ssinuco** [comment]
![US4](https://github.com/Laboratoria/curriculum/assets/16993732/d07ddf23-fe60-4c84-b717-fc28fbca687a)

**Comment by ssinuco** [comment]
![US1](https://github.com/Laboratoria/curriculum/assets/16993732/c4acb543-a422-4e79-ab6c-53c656a7ee47)
