### ISSUE TITLE
Bug con test OA's de Web Api - Dataverse

### ISSUE THREAD

**Issue by ChristianRL23** [Laboratoria/curriculum#1757]
El test: **"Se registra un Event Listener con un parámetro de evento"** falla cuando se pasa el nombre de una función al eventListener.

![image](https://github.com/Laboratoria/curriculum/assets/87323279/889c4f18-4a5e-4e52-b5a3-6a3be342d6c0)
![image (1)](https://github.com/Laboratoria/curriculum/assets/87323279/137a0f86-0fbf-4b17-9394-1c248a13509b)

Caso contrario cuando se define ahí mismo la función o una función anónima la llama:

![image](https://github.com/Laboratoria/curriculum/assets/87323279/eb8f1533-4b49-40fd-a154-3347b15fdfb5)
![image](https://github.com/Laboratoria/curriculum/assets/87323279/55183923-4b75-42d8-abf8-2a3758b8bd74)

**Comment by vivieall** [comment]
**Bug verificado**
![image](https://github.com/Laboratoria/curriculum/assets/13903491/247f45f4-9e23-488d-b870-01fb9e84fca4)

Se añadirá una validación adicional a las condicionales de dicho test que valida si el segundo argumento es una referencia a una función por su nombre.
