### ISSUE TITLE
Changes to Movie Challenge without framework

### ISSUE THREAD

**Issue by unjust** [Laboratoria/curriculum#1780]
Las sugerencias:
* cambiar la API de OMDB a TMDB
* traer las historias de usuario de MOvie Challenge con Framework como:
1: listado de películas
2: detalle de cada película

añadir que deben hacer testing
debe estar desplegada

[Usamos este PR ](https://github.com/Laboratoria/SAP012-movie-challenge/pull/1#pullrequestreview-1928876804)como base de los cambios.

**Comment by moniyama** [comment]
hemos hecho otros dos cambios 
- agregar boilerplate : https://github.com/Laboratoria/SAP012-movie-challenge/pull/2
- SPA: sugerido con hashchange y guide ruoter como hacker edition https://github.com/Laboratoria/SAP012-movie-challenge/pull/3

**Comment by marianaLz** [comment]
@MarciaMillanao ojo aquí, por favor
