### ISSUE TITLE
Ajustar OAs de Typescript

### ISSUE THREAD

**Issue by ssinuco** [Laboratoria/curriculum#1783]
De acuerdo a los modelos/tipos/interfaces de las implementaciones de los proyectos de la ruta de frontend

- [Movie Challenge con Angular](https://github.com/Laboratoria/impl-movie-challenge-fw-angular/tree/main/src/models)
- [Burger Queen API Client con Angular](https://github.com/Laboratoria/impl-burger-queen-api-client-angular/tree/master/BurgerQueen/src/app/shared/models)
- [Burger Queen API Client con React](https://github.com/Laboratoria/Impl-Burger-Queen-Api-Client-React-TS/blob/main/src/models/)

Se evidencia que los OAs de typescript deberian ajustarse para estos proyectos sean unicamente:

typescript:
  title: Typescript

typescript/basic-types:
  title: Tipos básicos

typescript/basic-types/primitives:
  title: Tipos primitivos
  links:
    - title: Documentación oficial de Typescript
      url: https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#the-primitives-string-number-and-boolean

typescript/basic-types/arrays:
  title: Arreglos
  links:
    - title: Documentación oficial de Typescript
      url: https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#arrays

typescript/basic-types/functions:
  title: Funciones
  links:
    - title: Documentación oficial de Typescript
      url: https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#functions
    - title: Documentación oficial de Typescript
      url: https://www.typescriptlang.org/docs/handbook/2/functions.html

typescript/basic-types/object-types:
  title: Tipos Objetos
  links:
    - title: Documentación oficial de Typescript
      url: https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#object-types
    - title: Documentación oficial de Typescript
      url: https://www.typescriptlang.org/docs/handbook/2/objects.html

typescript/basic-types/union-types:
  title: Tipos Union
  links:
    - title: Documentación oficial de Typescript
      url: https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#union-types

typescript/basic-types/interfaces:
  title: Interfaces
  links:
    - title: Documentación oficial de Typescript
      url: https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#interfaces

typescript/basic-types/enums:
  title: Enums
  links:
    - title: Documentación oficial de Typescript
      url: https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#enums

**Comment by unjust** [comment]
Los proyectos ahora tienen todo de typescript como OA 
https://github.com/Laboratoria/curriculum/blob/main/projects/04-burger-queen-api-client/project.yml#L26
Hay que elegir solo los OAs que @ssinuco esta proponiendo arriba, y editar los `project.yml` para solo tener los llaves de OAs individuales que queremos https://github.com/Laboratoria/curriculum/blob/main/learning-objectives/data.yml#L407
