### ISSUE TITLE
Update UXD curriculum

### ISSUE THREAD

**Issue by lisperaza** [Laboratoria/curriculum#1796]
Para UXD007 (cohort actual) decidimos fusionar los proyectos UXploradoras UI + UXploradoras UI en uno solo, debido a los aprendizajes del cohort anterior. Entonces mi duda es: modificamos uno de estos proyectos o prefieren crear otro con los nuevos OAs? se necesita para la próxima semana

Aquí el enunciado del [proyecto actual](https://bootcamp-uxd.gitbook.io/book-tecnico-uxd/proyectos-bootcamp/uxploradoras), no está en Curriculum aún.

Como referencia, los enunciados de [UXploradoras UI ](https://curriculum.laboratoria.la/es/projects/uxploradoras-ui)y [UXploradoras UX](https://curriculum.laboratoria.la/es/projects/uxploradoras-ux), ambos existen en Curriculum.

**Comment by unjust** [comment]
@lisperaza creo podemos generar UXploradoras aparte y despues deprecar lo de UI y UX.
Por eso, en un PR, hay que:

1. Generar un nuevo carpeta para el proyecto en /projects
2. Crear el nuevo readme
3. poner los OAs en project.yml
