### ISSUE TITLE
Opciones para escribir tests para Fleet Management

### ISSUE THREAD

**Issue by unjust** [Laboratoria/curriculum#1809]
Queremos probar integration tests de Fleet Management que idealmente son agnostica de lenguaje. Este puede ser mucho de pedit, pero vamos probando algunas ideas:

- [ ] probando con Postman y verificando si puede ser algunos tests minimo en el free tier
- [ ] pensamos que no seria mal crear tests en JS que puede interactuar con el API en cualquier lenguaje, al menos las estudiantes estan familiarizado con javascript, el punto de los tests son para probar la comportamiento de su API, no desarrollar los tests
- [x] usamos playwright para pruebas https://playwright.dev/docs/api-testing https://github.com/Laboratoria/impl-fleet-management-api-py-flask/pull/20

**Comment by unjust** [comment]
Creo estas pruebas son para confirmar que su API conforme a los criterios, similar a los tests en BQ API (que tambien vamos a renovar). Por ejemplo, que devuelva data en una estructura array y con un status particular, obedece las parametros de paginacion y otros. Por eso debemos definir mejor que sus rutas estan definidos en algun manera y no deja abierto - por ejemplo /taxis /locations/[taxt_id]etc.
Creo aun ellas pueden escribir unit tests, y tambien puede escribir tests de integracion en su propio framework (como con el Flask client o en Django) , quiza hay casos que no son cubiertos con los tests que entregamos. Creo lo que vamos entregar con el proyecto son solo para darnos y ellas un señal / respuesta rapida si van bien con su API o no, pero no reemplaza todo el testing.

**Comment by cros410** [comment]
He realizado una prueba de concepto que responde al punto:
- [ ] Probando con Postman y verificando si puede ser algunos tests minimo en el free tier

La implementación y PR se encuentra [aquí](https://github.com/Laboratoria/impl-fleet-management-api-node/pull/1)

@unjust creo que esto puede validar lo que hemos conversado y atacar las pruebas e2e de forma agnóstica al lenguaje de implementación y dejar las unitarias y de integridad de datos a cada lenguaje con su framework correspondiente.
Para ponernos de acuerdo con las estructuras de consulta y respuesta podemos usar la [documentación](https://app.swaggerhub.com/apis-docs/ssinuco/FleetManagementAPI/1.0.0#/) que compartió @ssinuco de todas maneras se puede convertir la documentación armada en Postman a Swagger [con esta herramienta web](https://metamug.com/util/postman-to-swagger/)

**Comment by cros410** [comment]
Teniendo como base esta documentación creo que hay algo que tenemos que terminar ponernos de acuerdo:

1)  Puerto compartido para todas las estudiantes -> Sugerencia el 8080
2) Documentación del api. Según hemos venido conversando

**Comment by cros410** [comment]
Teniendo como base esta documentación creo que hay algo que tenemos que terminar ponernos de acuerdo:

1) Puerto compartido para todas las estudiantes -> Sugerencia el 8080
2) Documentación del api. Según hemos venido conversando nos vamos a guiar de la siguiente [documentación](https://app.swaggerhub.com/apis-docs/ssinuco/FleetManagementAPI/1.0.0#/). Aquí tengo unas sugerencias
- Podemos ponerle el prefijo de `/auth` para que esté bajo un contexto
![image](https://github.com/Laboratoria/curriculum/assets/14276617/cc375a19-dfe5-410d-93ee-9f595b2a84ee)
- Solo dejar esta ruta con los parámetros de `page` y `limit`
![image](https://github.com/Laboratoria/curriculum/assets/14276617/29960d87-a4b2-4a33-a68b-37aa9a11de1a)
- Cambiar para que tanto el taxiId, date, page y limit se envíen por query para respetar la jerarquía en la URL. Adicionalmente haría la aclaración del formato de la fecha algo como `DD-MM-YYYY`
![image](https://github.com/Laboratoria/curriculum/assets/14276617/96998e90-8d85-48eb-a143-99a0b0480478)
- Mismos comentarios que el punto anterior
![image](https://github.com/Laboratoria/curriculum/assets/14276617/2ea42dc3-0942-4350-9ee1-e6d13fb30678)
- Nos tenemos que poner de acuerdo sobre las estructuras de respuesta en todos los endpoints. Creo que solo hay una diferencia entre la respuesta de la historia 3 y 4. Sugiero que nos quedemos con la de la historía número 4 donde la placa se incluye dentro del contenido
![image](https://github.com/Laboratoria/curriculum/assets/14276617/151b5a1f-3102-44cf-823c-c9f7149e5d27)
![image](https://github.com/Laboratoria/curriculum/assets/14276617/f5b3caed-9d9f-405f-a4e1-dc27bd9ee665)

Con estos cambios creo que podemos armar bien el contenido de las pruebas de postman.
@unjust 
@ssinuco 
Compartir esto de igual manera con los responsables de los otros lenguajes para poder avanzar con esto

**Comment by unjust** [comment]
@cros410 estoy de acuerdo con casi todos los cambios (formato de fecha, consistencia de data en HU3 y HU$, omitir query como parametro)
Quiza la unica para mi discutir es que` trajectories/{{taxiId}}` creo semanticamente tiene sentido ponerlo en el url y me gusta que tienen experiencia con paramteros en el url y no solo search params. Podemos definir also como  por defecto devuelva los trajectories de ultima dia o misma dia (pues la data es bien viejo enctonces no devuelva nada si es mismo dia).
Pero estoy flexible en este idea si pensamos mejor dejarlo como query param.

**Comment by davidgranados** [comment]
@unjust @cros410 creo que  `trajectories/{{taxiId}} `  no tiene mucho sentido... si en el path param va el taxi id no debería ser `taxis/{{taxiId}}/trajectories` ?

**Comment by unjust** [comment]
Ok entiendo @davidgranados. Veo los query params mas como opcionales y filtros.
Me gusta la idea de `taxis/{{taxiId}}/trajectories` porque ahora no hay oportunidad usar path parameters en el proyecto.

Si quedamos con `trajectories/`,  me pregunto si el endpoint `trajectories/` sin query params debe retornar algo, no? 
Ahora en [la historia de usuario](https://github.com/Laboratoria/curriculum/tree/main/projects/05-fleet-management-api#historia-de-usuario-3-endpoint-historial-de-ubicaciones) creo `taxiId` y `date` son requeridos o no definimos que `trajectories/` retorna algo sin ellos. Me parece un poco rara.

**Comment by cros410** [comment]
@unjust  dentro del contexto de usuario si hay oportunidad de usar `path parameters`

<img width="361" alt="image" src="https://github.com/Laboratoria/curriculum/assets/14276617/7972b4ab-fcd7-4319-9184-be8fed24c5a7">

Estoy de acuerdo con @davidgranados sobre las dos opciones que tenemos para la HU3 

a) `/taxis/{{taxiId}}/trajectories?date=02-02-2008`
b) `/trajectories?taxiId={{taxiId}}&date=02-02-2008`

Hasta el momento cuando me a tocado guiar a estudiantes he optado por la (b). Según los GIF que a sumado @ssinuco cobra más sentido la (a) porque no hay caso de uso para solo listar toas las trayectorias sino que siempre se necesitan en base a un taxi en especifico.
Lo que si recomendaría como comenta @unjust es mencionar que todos los parámetros por query son opcionales y de no enviar algunos tener valores con defecto como el `pageSize` y `pageNumber` y otro no como el `date` y posiblemente el `taxiId`
