### ISSUE TITLE
Crear proyecto de Salesforce

### ISSUE THREAD

**Issue by unjust** [Laboratoria/curriculum#1858]
- [ ] Readme basico @marianaLz con contenido con estes links 
https://trailhead.salesforce.com/users/marianalz/trailmixes/laboratoria-javascript-developer
https://trailhead.salesforce.com/users/marianalz/trailmixes/laboratoria-platform-developer
- [ ] Nivel de proyecto alto o Upskilling
- [ ] proyect.yml con flag salesforce platform `salesforce-platform` `salesforce-js`

**Comment by marianaLz** [comment]
# Programa de Acompañamiento Salesforce

Este programa ofrece dos rutas especializadas para desarrolladoras interesadas en profundizar sus habilidades en la plataforma Salesforce: **Platform Developer** y **JavaScript Developer**. A continuación, se detallan las habilidades y conocimientos clave para cada rol.

## Platform Developer en Salesforce

### Descripción del Rol
Un Salesforce Platform Developer se centra en la construcción y personalización de aplicaciones en la plataforma Salesforce, utilizando herramientas y lenguajes específicos como Apex y Visualforce. Este rol implica desarrollar soluciones robustas que se integren perfectamente con la plataforma Salesforce.

### Habilidades y Conocimientos Necesarios

1. **Apex**: Lenguaje de programación similar a Java, utilizado para el desarrollo del lado del servidor en Salesforce.
2. **Visualforce**: Framework para la creación de interfaces de usuario personalizadas.
3. **SOQL y SOSL**: Lenguajes de consulta para buscar información en la base de datos de Salesforce.
4. **Lightning Components**: Framework basado en componentes para la creación de interfaces de usuario modernas y dinámicas.
5. **Configuración de Salesforce**: Comprensión de cómo configurar Salesforce para aprovechar al máximo las características estándar.
6. **Automatización de Procesos**: Uso de flujos de trabajo, procesos y disparadores para automatizar tareas dentro de Salesforce.
7. **Integraciones**: Conexión de Salesforce con otros sistemas utilizando APIs y herramientas de integración.

#### [Acceso al Trailmix de Platform Developer](https://trailhead.salesforce.com/users/marianalz/trailmixes/laboratoria-platform-developer)

## JavaScript Developer en Salesforce

### Descripción del Rol
Un Salesforce JavaScript Developer se enfoca principalmente en el desarrollo del lado del cliente utilizando JavaScript, con especial énfasis en Lightning Web Components (LWC), que es el estándar actual para la creación de componentes en la interfaz de usuario de Salesforce.

### Habilidades y Conocimientos Necesarios

1. **JavaScript**: Conocimiento profundo de JavaScript, incluyendo ES6+.
2. **Lightning Web Components (LWC)**: Framework para desarrollar componentes reutilizables en la interfaz de usuario de Salesforce.
3. **HTML y CSS**: Conocimientos sólidos en tecnologías web fundamentales.
4. **Salesforce APIs**: Comprensión de cómo interactuar con Salesforce mediante APIs desde el lado del cliente.
5. **Debugging y Testing**: Habilidades para depurar y probar componentes JavaScript.
6. **Configuración de Salesforce**: Conocimiento de cómo los componentes JavaScript interactúan con la configuración y los datos de Salesforce.

#### [Acceso al Trailmix de JavaScript Developer](https://trailhead.salesforce.com/users/marianalz/trailmixes/laboratoria-javascript-developer)

## Comparación y Superposiciones

- **Superposiciones**: Ambos roles requieren un buen entendimiento de la plataforma Salesforce, su modelo de datos y sus capacidades de integración.
- **Diferencias Clave**: El Platform Developer se centra más en el desarrollo del lado del servidor y la lógica de negocio con Apex, mientras que el JavaScript Developer se enfoca en la experiencia del usuario y la interfaz del cliente con JavaScript y LWC.

Cada ruta está diseñada para equipar a las desarrolladoras con las habilidades necesarias para sobresalir en sus roles respectivos, contribuyendo tanto al desarrollo backend como frontend en el ecosistema Salesforce.
